import test,{before,after} from 'node:test';import assert from 'node:assert/strict';
import {createHandler,validatePacket} from '../server/handler.mjs';import {createDevServer} from '../scripts/dev.mjs';import {createMemoryStore} from './helpers/memory-store.mjs';import {fresh} from '../docs/app/model.js';
const env={DATABASE_URL:'postgresql://test:test@unit.neon.tech/db',TEACHER_PASSWORD:'TEST-only-password-long-123',CLASS_CODE:'TEST-classe-123',CRON_SECRET:'test-only-cron-secret-32-characters-or-more'};
let srv,base;const store=createMemoryStore();
before(async()=>{srv=createDevServer(createHandler({env,store,log:()=>{}}));await new Promise(r=>srv.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${srv.address().port}`;});after(async()=>{srv.closeAllConnections();await new Promise(r=>srv.close(r));});
const call=(p,method='GET',body,headers={})=>fetch(base+'/api/'+p,{method,headers:{'Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});
async function enroll(alias='TEST-A'){const r=await call('enroll','POST',{alias,classCode:env.CLASS_CODE});assert.equal(r.status,201);return r.json();}
async function login(){const r=await call('teacher/login','POST',{password:env.TEACHER_PASSWORD});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];}
const packet=(order=1)=>({packetId:'packet-test-'+order,order,state:fresh('TEST-A')});
test('configuration et santé sans divulgation de clé',async()=>{const r=await call('config');const s=await r.text();assert.equal(r.status,200);assert(!s.includes(env.CLASS_CODE));assert(!s.includes(env.TEACHER_PASSWORD));assert.equal((await call('health')).status,200);});
test('données professeur protégées',async()=>assert.equal((await call('teacher/learners')).status,401));
test('mauvais code refusé',async()=>assert.equal((await call('enroll','POST',{alias:'A1',classCode:'not-good'})).status,403));
test('origine étrangère refusée',async()=>assert.equal((await call('enroll','POST',{alias:'A1',classCode:env.CLASS_CODE},{Origin:'https://bad.test'})).status,403));
test('envoi sans jeton interdit',async()=>assert.equal((await call('events','POST',packet())).status,401));
test('envoi suivi et validation optimiste',async()=>{const e=await enroll(),state=fresh('TEST-A');state.responses['diag-demarrer']={input:{code:'function annoncerDepart(){console.log("La partie commence");}annoncerDepart();'},done:true,tries:1,hints:0};state.revision=1;const data={packetId:'packet-correct-test',order:1,state};const r=await call('events','POST',data,{Authorization:'Bearer '+e.token});assert.equal(r.status,200);const cookie=await login();const detail=await (await call('teacher/learner/'+e.studentId,'GET',null,{Cookie:cookie})).json();assert.equal(detail.learner.summary.diagnostic,null);assert.equal(detail.learner.core_completed,1);const stale=await call('teacher/learner/'+e.studentId,'POST',{validation:'valide',note:'clair',expectedRevision:0,expectedRunId:state.runId},{Cookie:cookie});assert.equal(stale.status,409);const good=await call('teacher/learner/'+e.studentId,'POST',{validation:'valide',note:'clair',expectedRevision:1,expectedRunId:state.runId},{Cookie:cookie});assert.equal(good.status,200);});
test('import ancien BIOS non accepté dans ce serveur',()=>assert.throws(()=>validatePacket({...packet(),state:{schema:1,lessonId:'R-260929',runId:'test-run'}})));
test('jeton valide ne permet pas de voir la liste professeur',async()=>{const e=await enroll('TEST-B');assert.equal((await call('teacher/learners','GET',null,{Authorization:'Bearer '+e.token})).status,401);});
test('suppression d’un seul dossier et déconnexion',async()=>{const e=await enroll('TEST-C'),cookie=await login();assert.equal((await call('teacher/learner/'+e.studentId,'DELETE',null,{Cookie:cookie})).status,200);assert.equal((await call('events','POST',packet(),{Authorization:'Bearer '+e.token})).status,401);assert.equal((await call('teacher/logout','POST',{}, {Cookie:cookie})).status,200);assert.equal((await call('teacher/learners','GET',null,{Cookie:cookie})).status,401);});
test('cron protégé',async()=>assert.equal((await call('cron')).status,401));
test('corps HTML non accepté',async()=>{const e=await enroll('TEST-D');const r=await fetch(base+'/api/events',{method:'POST',headers:{Authorization:'Bearer '+e.token,'Content-Type':'text/plain'},body:'x'});assert.equal(r.status,415);});
