import test,{before,after} from 'node:test';import assert from 'node:assert/strict';
import{createHandler}from'../server/handler.mjs';import{createDevServer}from'../scripts/dev.mjs';import{createMemoryStore}from'./helpers/memory-store.mjs';import{createAssessmentMemory}from'./helpers/assessment-memory.mjs';import{fresh}from'../docs/app/model.js';import{correctionExample}from'../server/grade.mjs';
const env={DATABASE_URL:'postgresql://test:test@fake.neon.tech/db',TEACHER_PASSWORD:'TEST-only-password-long-123',CLASS_CODE:'TEST-classe-123',CRON_SECRET:'test-only-cron-secret-32-characters-or-more'};
const store=createMemoryStore(),assessmentStore=createAssessmentMemory(store);let srv,base;let now=1789900000000;
before(async()=>{srv=createDevServer(createHandler({env,store,assessmentStore,clock:()=>now,log:()=>{}}));await new Promise(r=>srv.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+srv.address().port;});after(()=>{srv.closeAllConnections();srv.close();});
const call=(path,method='GET',body,headers={})=>fetch(base+'/api/'+path,{method,headers:{'Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});
async function student(){const r=await call('enroll','POST',{alias:'DEMO',classCode:env.CLASS_CODE});const d=await r.json();d.h={Authorization:'Bearer '+d.token};return d;}
async function teacher(){const r=await call('teacher/login','POST',{password:env.TEACHER_PASSWORD});return {Cookie:r.headers.get('set-cookie').split(';')[0]};}
function state(){const s=fresh('Faux alias');s.responses={};for(const [id,file] of [['diag-demarrer','depart.js'],['diag-saluer','saluer.js'],['diag-doubler','doubler.js'],['diag-retour','additionner.js']])s.responses[id]={input:{code:correctionExample[file]},done:true};return s;}
async function submit(e,s=state(),requestId='submit-test-1'){await call('assessment','POST',{action:'start'},e.h);const r=await call('assessment','POST',{action:'submit',state:s,requestId},e.h);assert.equal(r.status,201);return r.json();}
const detail=(e,h,sub='')=>call('teacher/assessment?action=detail&id='+e.studentId+(sub?'&submission='+sub:''),'GET',null,h).then(r=>r.json());
test('assessment et export refusés sans authentification',async()=>{assert.equal((await call('assessment')).status,401);assert.equal((await call('teacher/assessment?action=list')).status,401);assert.equal((await call('teacher/assessment?action=export&id='+'a'.repeat(24))).status,401);});
test('démarrage unique et horloge serveur',async()=>{const e=await student();const a=await(await call('assessment','POST',{action:'start'},e.h)).json();now+=4000;const b=await(await call('assessment','POST',{action:'start'},e.h)).json();assert.equal(a.started,b.started);assert.equal(a.attempt,1);});
test('remise figée pré-corrigée avec alias de connexion',async()=>{const e=await student(),r=await submit(e),h=await teacher(),d=await detail(e,h);assert.equal(d.evaluation.id,r.id);assert.equal(d.evaluation.grade.total,20);assert.equal(d.evaluation.state.alias,'DEMO');assert.equal(d.evaluation.grade.status,'a-relire');});
test('la réponse élève ne contient ni corrigé ni note',async()=>{const e=await student();await submit(e);const r=await call('assessment','GET',null,e.h),d=await r.json();assert(d.session.finalId);assert(!JSON.stringify(d).includes('Indicateur observé'));assert(!Object.hasOwn(d,'grade'));assert(d.finalState.responses['diag-saluer']);});
test('remise idempotente : même reçu, pas de doublon',async()=>{const e=await student(),s=state(),a=await submit(e,s);const b=await(await call('assessment','POST',{action:'submit',requestId:'submit-test-1',state:s},e.h)).json();assert.equal(a.id,b.id);assert.equal((await assessmentStore.history(e.studentId,store.data.learners.get(e.studentId).scope)).length,1);});
test('identifiant réutilisé avec une autre copie refusé',async()=>{const e=await student(),s=state();await submit(e,s);s.responses['diag-retour'].input.code='';assert.equal((await call('assessment','POST',{action:'submit',requestId:'submit-test-1',state:s},e.h)).status,409);});
test('une seconde remise n’écrase pas la première',async()=>{const e=await student(),r=await submit(e);const b=await(await call('assessment','POST',{action:'submit',requestId:'other-test-1',state:fresh('DEMO')},e.h)).json();assert.equal(r.id,b.id);assert.equal(b.alreadySubmitted,true);});
test('sauvegarde de cours récupérable même sans paquet automatique',async()=>{const e=await student(),s=state();s.responses['entrainement-1']={input:{code:'function estMajeur(age){return age>=18;}'}};const r=await call('assessment','POST',{action:'save',requestId:'save-test-1',state:s},e.h);assert.equal(r.status,201);const d=await(await call('assessment','GET',null,e.h)).json();assert.equal(d.state.responses['entrainement-1'].input.code,s.responses['entrainement-1'].input.code);assert.equal(d.session,null);});
test('copie de cours ne modifie pas le diagnostic figé',async()=>{const e=await student(),r=await submit(e);await call('assessment','POST',{action:'save',requestId:'save-test-2',state:fresh('DEMO')},e.h);const d=await detail(e,await teacher());assert.equal(d.evaluation.id,r.id);assert.equal(d.evaluation.grade.total,20);});
test('correction manuelle versionnée puis export Excel avec nouveau total',async()=>{const e=await student(),r=await submit(e),h=await teacher(),d=await detail(e,h);const items=d.evaluation.grade.items.map(i=>({...i,comment:''}));items[0].point=0;items[0].comment='Déclaration à reprendre après entretien.';const body={action:'review',submissionId:r.id,expectedVersion:0,status:'valide',note:'Bon travail, reprends la déclaration.',items};const saved=await call('teacher/assessment','POST',body,h);assert.equal(saved.status,200);const g=await saved.json();assert.equal(g.review.total,19);assert.equal(g.reviewVersion,1);assert.equal((await call('teacher/assessment','POST',body,h)).status,409);const ex=await call('teacher/assessment?action=export&id='+e.studentId+'&format=files','GET',null,h);assert.equal(ex.status,200);const f=(await ex.json()).files;assert(Object.keys(f).some(k=>k.endsWith('.xlsx')));const correction=JSON.parse(Buffer.from(f[Object.keys(f).find(k=>k.endsWith('correction.json'))],'base64'));assert.equal(correction.review.total,19);assert.equal(correction.automatic.total,20);const q=await detail(e,h);assert.equal(q.audit.length,1);});
test('changement de point sans motif refusé',async()=>{const e=await student(),r=await submit(e),h=await teacher(),d=await detail(e,h);const items=d.evaluation.grade.items.map(i=>({...i,comment:''}));items[0].point=0;assert.equal((await call('teacher/assessment','POST',{action:'review',submissionId:r.id,expectedVersion:0,status:'valide',note:'',items},h)).status,400);});
test('réouverture conserve l’original et crée une tentative 2',async()=>{const e=await student(),r=await submit(e),h=await teacher();assert.equal((await call('teacher/assessment','POST',{action:'reopen',learnerId:e.studentId,reason:'Reprise accompagnée'},h)).status,200);now+=5000;const second=await submit(e,state(),'submit-test-2'),d=await detail(e,h);assert.notEqual(r.id,second.id);assert.equal(d.evaluation.attempt,2);assert.equal(d.history.length,2);const old=await detail(e,h,r.id);assert.equal(old.evaluation.id,r.id);assert.equal(old.audit[0].action,'reopen');});
test('un élève ne peut pas lire la correction de son camarade',async()=>{const a=await student(),b=await student();await submit(a);const r=await call('teacher/assessment?action=detail&id='+a.studentId,'GET',null,b.h);assert.equal(r.status,401);});
test('dossier d’une autre classe refusé',async()=>{const e=await student();await submit(e);store.data.learners.get(e.studentId).scope='autre-classe';const r=await call('teacher/assessment?action=detail&id='+e.studentId,'GET',null,await teacher());assert.equal(r.status,404);});
test('API de correction refuse point hors barème',async()=>{const e=await student(),r=await submit(e),h=await teacher(),d=await detail(e,h);const items=d.evaluation.grade.items;items[0].point=9;assert.equal((await call('teacher/assessment','POST',{action:'review',submissionId:r.id,expectedVersion:0,status:'valide',note:'',items},h)).status,400);});
test('export non remis contient NE et aucune copie originale inventée',async()=>{const e=await student(),h=await teacher();const r=await call('teacher/assessment?action=export&id='+e.studentId+'&format=files','GET',null,h);assert.equal(r.status,200);const d=await r.json();assert(Object.keys(d.files).some(k=>k.endsWith('feuille_correction.xlsx')));assert(!Object.keys(d.files).some(k=>k.endsWith('rendu_original.json')));});
test('requête intersite refuse une correction même avec cookie',async()=>{const h=await teacher();assert.equal((await call('teacher/assessment','POST',{action:'review'}, {...h,Origin:'https://evil.example'})).status,403);});

test('une nouvelle remise ne peut pas choisir le barème ancien depuis le navigateur',async()=>{const e=await student(),s=state();s.diagnosticVersion='fonctions-261001-v1';await submit(e,s);const d=await detail(e,await teacher());assert.equal(d.evaluation.grade.version,'fonctions-261001-pratique-v2');assert.equal(d.evaluation.state.diagnosticVersion,'fonctions-261001-pratique-v2');assert.equal(d.evaluation.grade.total,20);});
