import test from 'node:test';import assert from 'node:assert/strict';
import {parseExpression,evaluate,truthCases,testProgram,parseProgram} from '../docs/app/logic.js';
import {fresh,sanitizeState,checkStep,summary,timetable,bonusUnlocked} from '../docs/app/model.js';
import {STEPS,BLOCKS} from '../docs/app/content.js';
for(const [exp,result] of [['true && true',true],['true && false',false],['false && true',false],['false && false',false],['true || false',true],['false || true',true],['true || true',true],['false || false',false],['!true',false],['!false',true],['20 >= 20',true],['20 > 20',false],['14 === 14',true],['14 !== 14',false],['!(true && false)',true],['(true || false) && !true',false]])test('expression : '+exp,()=>assert.equal(evaluate(parseExpression(exp)),result));
for(const s of ['fetch("https://example.com")','while (true) {}','new Function("return 1")','globalThis.document.cookie','A = true','true & false','import("./x")'])test('code hors périmètre refusé : '+s,()=>assert.throws(()=>evaluate(parseExpression(s),{})));
test('erreur sur booléens implicites',()=>assert.throws(()=>evaluate(parseExpression('1 && true'))));
test('variable inconnue et garde de profondeur',()=>{assert.throws(()=>evaluate(parseExpression('a'),{}));assert.throws(()=>parseExpression('('.repeat(100)+'true'+')'.repeat(100)));});
test('huit combinaisons uniques',()=>assert.equal(new Set(truthCases(['A','B','C']).map(JSON.stringify)).size,8));
for(const [kind,expr,total] of [['and','aCarte && aReserve',4],['combined','(aTicket || estInvite) && !estFerme',8],['threshold','points >= 14 && aAutorisation',6]])test('code validé sur tous les cas : '+kind,()=>{const r=testProgram(`if (${expr}) { console.log("OK"); } else { console.log("REFUS"); }`,kind);assert(r.ok);assert.equal(r.rows.length,total);});
test('mauvais OU détecté par contre-exemples',()=>{const r=testProgram('if (aCarte || aReserve) { console.log("OK"); } else { console.log("REFUS"); }','and');assert(!r.ok);assert.equal(r.rows.filter(r=>!r.ok).length,2);});
test('seuil strict détecté exactement à 14',()=>{const r=testProgram('if (points > 14 && aAutorisation) { console.log("OK"); } else { console.log("REFUS"); }','threshold');assert.equal(r.rows.filter(r=>!r.ok).length,1);assert.equal(r.rows.find(r=>!r.ok).vars.points,14);});
test('aucune exécution libre et syntaxe manquante signalée',()=>{assert(!testProgram('fetch("x")','and').ok);assert(!testProgram('if () {}','and').ok);});
test('planning relatif si début absent',()=>{assert(timetable()[0].label.startsWith('T+'));assert.equal(timetable().at(-1).to,175);assert.equal(timetable('09:00')[0].label,'09h00–09h20');});
test('diagnostic : passer garde un échec à reprendre, pas une maîtrise',()=>{const step=STEPS[0];const r=checkStep(step,{code:'',skip:'yes'});assert(r.ok);assert.equal(r.mastery,false);assert.equal(r.skipped,true);});
test('un QCM pédagogique n’est pas validé avec des champs vides',()=>assert(!checkStep(STEPS.find(s=>s.id==='bool-seuil'),{}).ok));
test('table ET doit couvrir quatre cases',()=>{const step=STEPS.find(s=>s.id==='et-table');assert(checkStep(step,{r0:'false',r1:'false',r2:'false',r3:'true'}).ok);assert(!checkStep(step,{r0:'false'}).ok);});
test('bonus verrouillé au départ',()=>assert(!bonusUnlocked(fresh('TEST'))));
test('import d’une autre séance rejeté',()=>assert.throws(()=>sanitizeState({...fresh(),lessonId:'R-260929'})));
test('sanitisation bornée et sans jeton exporté',()=>{const s=fresh('TEST');s.token='secret';s.responses['diag-lire']={input:{d1:'x'.repeat(10000)},tries:4,done:true};const r=sanitizeState(s);assert.equal(r.token,undefined);assert.equal(r.responses['diag-lire'].input.d1.length,2000);});
test('recalcul de score côté modèle',()=>{const s=fresh('TEST');s.pm09=5;assert.equal(summary(s).pm09,0);});
test('identifiants tous distincts, objectifs corrects',()=>{assert.equal(new Set(STEPS.map(s=>s.id)).size,STEPS.length);assert.equal(BLOCKS.reduce((a,b)=>a+b.minutes,0),175);});
