import test from 'node:test';
import assert from 'node:assert/strict';
import {transferFixture,png} from './fixtures/lesson-transfer.mjs';
import {readEditor,saveEditor,publishEditor,exportEditor} from '../server/lesson-editor.mjs';
import {ensureSection,synchronizeSpec,removeSection,removeItem,duplicateSection,starterFiles} from '../public/lesson-editor-model.js';
import {textDocument,renderRich,validateRich} from '../public/rich-document.js';
import {DraftWriter} from '../public/editor-save.js';
import {studentSpec} from '../server/generator.mjs';
import {validateReferences,decodePackage} from '../server/lesson-package.mjs';
import {preparePublication} from '../server/publication-readiness.mjs';
import {publishLesson} from '../server/domain.mjs';
import {beginUpload,writeChunk,previewTransfer,applyTransfer} from '../server/lesson-transfer.mjs';
import {sha256} from '../server/content-snapshots.mjs';
import {createApp} from '../server/app.mjs';
const close=async(...f)=>{for(const x of f)await x.store.close();};
const load=f=>readEditor(f.store,f.lesson.id,f.actor),save=(f,v)=>saveEditor(f.store,f.lesson.id,{token:v.token,spec:v.spec},f.actor);
const rich={type:'doc',content:[{type:'heading',attrs:{level:2},content:[{type:'text',text:'Comprendre'}]},{type:'paragraph',content:[{type:'text',text:'Texte enrichi',marks:[{type:'bold'},{type:'underline'}]},{type:'text',text:' lien',marks:[{type:'link',attrs:{href:'https://example.com'}}]}]},{type:'bulletList',content:[{type:'listItem',content:[{type:'paragraph',content:[{type:'text',text:'Premier point'}]}]}]},{type:'image',attrs:{src:'data:image/png;base64,'+png.toString('base64'),alt:'Un point',title:'Légende'}}]};

test('existing no-op is lossless; rich content and exact starter files persist',async()=>{const f=await transferFixture();try{let v=await load(f),before=structuredClone(v.spec);const same=await save(f,v);assert.equal(same.token,v.token);assert.deepEqual(same.spec,before);
 const b=v.spec.blocks.find(b=>b.phase==='understand');ensureSection(b,v.spec)[0].doc=rich;v.spec.editorVersion=1;const a=v.spec.activities.find(a=>a.id==='guided');const code='\n\t.carte {\n  color: red;\n}\n';a.starter=code;synchronizeSpec(v.spec);v=await save(f,v);const reload=await load(f);assert.deepEqual(reload.spec.blocks.find(x=>x.id===b.id).editor.items[0].doc,rich);assert.equal(reload.spec.activities.find(x=>x.id===a.id).starter,code);assert.match(renderRich(rich),/<strong>/);assert.match(renderRich(rich),/<figcaption>Légende/);assert.equal(v.token,reload.token);
 a.starter='';v.spec.activities.find(x=>x.id===a.id).starter='';v=await save(f,v);assert.equal(v.spec.activities.find(x=>x.id===a.id).starter,'');
 }finally{await close(f);}});

test('reorder, duplicate, remove blocks and remove all sections preserve identities and answers',async()=>{const f=await transferFixture();try{let v=await load(f);const b=v.spec.blocks.find(b=>b.activityIds.includes('guided')),original=structuredClone(v.spec.activities.find(a=>a.id==='guided'));ensureSection(b,v.spec);const copy=duplicateSection(v.spec,b.id);assert.notEqual(copy.id,b.id);assert.notEqual(copy.activityIds[0],b.activityIds[0]);assert.equal(v.spec.activities.find(a=>a.id===copy.activityIds[b.activityIds.indexOf(original.id)]).starter,original.starter);v.spec.blocks.reverse();v.spec.editorVersion=1;synchronizeSpec(v.spec);const ids=v.spec.blocks.map(b=>b.id);v=await save(f,v);assert.deepEqual(v.spec.blocks.map(b=>b.id),ids);assert.deepEqual(v.spec.activities.find(a=>a.id==='guided'),original);
 const block=v.spec.blocks.find(x=>x.id===b.id),item=ensureSection(block,v.spec).find(i=>i.kind==='rich');removeItem(v.spec,block,item.id);v=await save(f,v);assert.ok(!v.spec.blocks.find(x=>x.id===b.id).editor.items.some(i=>i.id===item.id));
 await f.store.insert('learning_progress',{id:'old-progress',classId:'A1',answers:{guided:'élève'}});for(const b of [...v.spec.blocks])removeSection(v.spec,b.id);v=await save(f,v);assert.equal(v.spec.blocks.length,0);assert.equal(v.spec.diagnostic.tasks.length,0);assert.equal(v.spec.diagnostic.rubric.length,0);assert.equal((await load(f)).spec.blocks.length,0);assert.equal((await f.store.get('learning_progress','old-progress')).answers.guided,'élève');
 }finally{await close(f);}});

test('stale and concurrent saves conflict instead of restoring deleted sections',async()=>{const f=await transferFixture();try{const a=await load(f),b=structuredClone(a);a.spec.title='Premier';b.spec.title='Deuxième';const results=await Promise.allSettled([save(f,a),save(f,b)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.status,409);assert.equal((await load(f)).spec.title,'Premier');}finally{await close(f);}});

test('published edits remain draft; update preserves link and old learner work with new revision',async()=>{const f=await transferFixture();try{await preparePublication(f.store,f.lesson.id,{version:1},f.actor);await publishLesson(f.store,f.lesson.id,f.actor,{version:1,confirmed:true});const old=await f.store.get('lessons',f.lesson.id);await f.store.insert('learning_progress',{id:'student:'+old.versionId,classId:'A1',answers:{guided:'travail personnel'},completed:['guided']});let v=await load(f);v.spec.title='Titre modifié';v.spec.activities.find(a=>a.id==='guided').starter='';v=await save(f,v);const published=await f.store.get('lessons',f.lesson.id);assert.equal(published.versionId,old.versionId);assert.equal(published.title,old.title);assert.ok(published.editorDraftVersionId);const result=await publishEditor(f.store,f.lesson.id,{token:v.token,confirmed:true},f.actor);assert.equal(result.id,old.id);assert.equal(result.date,old.date);assert.notEqual(result.versionId,old.versionId);assert.equal(result.title,'Titre modifié');assert.equal((await f.store.get('learning_progress','student:'+old.versionId)).answers.guided,'travail personnel');assert.equal(await f.store.get('learning_progress','student:'+result.versionId),null);assert.equal((await f.store.get('lesson_versions',result.versionId)).spec.activities.find(a=>a.id==='guided').starter,'');}finally{await close(f);}});

test('rich draft and files round-trip between independent stores without the source',async()=>{const f=await transferFixture(),dest=await transferFixture();try{let v=await load(f);const b=v.spec.blocks.find(b=>b.phase==='understand');ensureSection(b,v.spec)[0].doc=rich;v.spec.editorVersion=1;v.spec.blocks.reverse();v.spec.activities.find(a=>a.id==='guided').starter='\n\t/* exact */\n';synchronizeSpec(v.spec);v=await save(f,v);const {bytes}=await exportEditor(f.store,f.lesson.id,{token:v.token},f.actor);const pack=await decodePackage(bytes);assert.ok(pack.lessons[0].payload.corpus.files.some(f=>f.path==='01_ELEVE/cours.html'));const transfer=await beginUpload(dest.store,{bytes:bytes.length,sha256:sha256(bytes)},dest.actor);for(let n=0;n<transfer.chunks;n++)await writeChunk(dest.store,transfer.id,n,bytes.subarray(n*transfer.chunkBytes,(n+1)*transfer.chunkBytes),dest.actor);const preview=await previewTransfer(dest.store,transfer.id,{},dest.actor);assert.equal(preview.canApply,true);const result=await applyTransfer(dest.store,transfer.id,{token:preview.token,confirmed:true},dest.actor);const reopened=await readEditor(dest.store,result.lessons[0].id,dest.actor);assert.deepEqual(reopened.spec.blocks.map(b=>b.id),v.spec.blocks.map(b=>b.id));const restoredRich=reopened.spec.blocks.find(x=>x.id===b.id).editor.items[0].doc;assert.deepEqual(restoredRich.content.slice(0,-1),rich.content.slice(0,-1));const image=restoredRich.content.at(-1);assert.match(image.attrs.src,/^\/api\/lesson-transfer-files\//);assert.equal((await dest.store.get('lesson_assets',image.attrs.src.split('/').at(-1))).base64,png.toString('base64'));assert.equal(reopened.spec.activities.find(a=>a.id==='guided').starter,'\n\t/* exact */\n');validateReferences(reopened.spec);}finally{await close(f,dest);}});

test('private rich corrections never enter the student projection; injected nodes and links are rejected',()=>{assert.throws(()=>validateRich({type:'doc',content:[{type:'script'}]}));assert.throws(()=>validateRich({type:'doc',content:[{type:'image',attrs:{src:'javascript:alert(1)'}}]}));assert.throws(()=>validateRich({type:'doc',content:[{type:'text',text:'x',marks:[{type:'link',attrs:{href:'javascript:alert(1)'}}]}]}));assert.equal(renderRich(textDocument('<script>alert(1)</script>')).includes('<script>'),false);const s=studentSpec({blocks:[],activities:[{richText:{reference:textDocument('secret'),instruction:textDocument('public')},tests:[],reference:'secret'}],diagnostic:{tasks:[]},teacherGuide:'secret'});assert.equal(s.activities[0].richText.reference,undefined);assert.equal(s.teacherGuide,undefined);});

test('DOM sources, including an empty main.js, use the actual starter field',()=>{const a={starter:'console.log(3);\n',workshop:{profile:'dom',files:[{path:'index.html',content:'<main>ok</main>'},{path:'style.css',content:'\n'},{path:'main.js',content:'obsolete'}]}};const files=starterFiles(a);assert.equal(files[2].get(),a.starter);files[2].set('');assert.equal(a.starter,'');assert.equal(a.workshop.files[2].content,'');files[0].set('');assert.equal(a.workshop.files[0].content,'');});

test('writer serializes delayed responses and keeps failed work dirty',async()=>{let state={text:'initial'},finish,calls=0,states=[];const writer=new DraftWriter({read:()=>state,token:'v1',onState:s=>states.push(s),write:async(spec,token)=>{calls++;if(calls===1){assert.equal(spec.text,'first');await new Promise(r=>finish=r);return {token:'v2'};}assert.equal(token,'v2');assert.equal(spec.text,'latest');return {token:'v3'};}});state.text='first';const pending=writer.save();state.text='latest';finish();await pending;assert.equal(calls,2);assert.equal(writer.dirty,false);assert.equal(writer.token,'v3');assert.equal(states.at(-1),'Enregistré');state.text='keep me';writer.write=async()=>{throw Error('offline');};await assert.rejects(()=>writer.save(),/offline/);assert.equal(writer.dirty,true);assert.equal(state.text,'keep me');assert.equal(states.at(-1),'Échec de l’enregistrement');});

test('editor API enforces role, class and preview redaction',async()=>{const f=await transferFixture(),server=createApp(f.store).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{const base='http://127.0.0.1:'+server.address().port;const unauth=await fetch(base+'/api/lessons/'+f.lesson.id+'/editor');assert.equal(unauth.status,401);await assert.rejects(()=>readEditor(f.store,f.lesson.id,{...f.actor,classId:'other'}));const login=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:'teacher',username:'professeur',password:'quality-preview-only'})});const cookie=login.headers.get('set-cookie').split(';')[0];const headers={'Content-Type':'application/json',cookie};const view=await(await fetch(base+'/api/lessons/'+f.lesson.id+'/editor',{headers})).json();const response=await fetch(base+'/api/lessons/'+f.lesson.id+'/editor/preview',{method:'POST',headers,body:JSON.stringify({token:view.token,spec:view.spec})});assert.equal(response.status,200);const s=await response.json();assert.equal(s.teacherGuide,undefined);assert.ok(s.activities.every(a=>!Object.hasOwn(a,'reference')));}finally{server.closeAllConnections();await new Promise(r=>server.close(r));await close(f);}});

test('a rich draft survives closing and reopening a real SQLite file',async()=>{
 const {openStore,TABLES}=await import('../server/store.mjs'),{mkdtemp,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path');
 const f=await transferFixture(),directory=await mkdtemp(join(tmpdir(),'editor-persistence-'));let disk;
 try{disk=await openStore({url:null,path:join(directory,'courses.sqlite')});for(const t of TABLES)for(const row of await f.store.readRows(t))await disk.insertRow(t,row);let v=await readEditor(disk,f.lesson.id,f.actor);v.spec.editorVersion=1;ensureSection(v.spec.blocks[0],v.spec)[0].doc=rich;v.spec.activities.find(a=>a.id==='guided').starter='\r\n\t/* CRLF */\r\n';v=await saveEditor(disk,f.lesson.id,{token:v.token,spec:v.spec},f.actor);await disk.close();disk=await openStore({url:null,path:join(directory,'courses.sqlite')});const restored=await readEditor(disk,f.lesson.id,f.actor);assert.equal(restored.token,v.token);assert.deepEqual(restored.spec,v.spec);assert.equal(restored.spec.activities.find(a=>a.id==='guided').starter,'\r\n\t/* CRLF */\r\n');}finally{await disk?.close();await f.store.close();await rm(directory,{recursive:true,force:true});}
});

test('publication rejection leaves the published selection and editable draft intact',async()=>{const f=await transferFixture();try{await preparePublication(f.store,f.lesson.id,{version:1},f.actor);await publishLesson(f.store,f.lesson.id,f.actor,{version:1,confirmed:true});let v=await load(f),old=await f.store.get('lessons',f.lesson.id);for(const b of [...v.spec.blocks])removeSection(v.spec,b.id);v=await save(f,v);await assert.rejects(()=>publishEditor(f.store,f.lesson.id,{token:v.token,confirmed:true},f.actor),e=>e.status===422);const current=await f.store.get('lessons',f.lesson.id);assert.equal(current.versionId,old.versionId);assert.equal(current.status,'published');assert.equal((await load(f)).spec.blocks.length,0);}finally{await close(f);}});

test('code editing preserves original and pasted CRLF, mixed newlines, tabs and empty files',async()=>{const {applyCodeChanges}=await import('../public/code-source.js');const source='\r\n\tone\r\ntwo\n';assert.equal(applyCodeChanges(source,[{from:2,to:5,text:'ONE'}]),'\r\n\tONE\r\ntwo\n');assert.equal(applyCodeChanges('old',[{from:0,to:3,text:'\nnew\n'}],'\r\n\tnew\r\n'),'\r\n\tnew\r\n');assert.equal(applyCodeChanges(source,[{from:0,to:10,text:''}]),'');});

test('remote replacement retires the draft pointer, retains its history and conflicts with the open editor',async()=>{const source=await transferFixture(),dest=await transferFixture();try{
 await preparePublication(dest.store,dest.lesson.id,{version:1},dest.actor);await publishLesson(dest.store,dest.lesson.id,dest.actor,{version:1,confirmed:true});let draft=await load(dest);draft.spec.title='Travail local à conserver';draft=await save(dest,draft);const retired=draft.versionId;
 let remote=await load(source);remote.spec.title='Contenu importé';remote=await save(source,remote);const {bytes}=await exportEditor(source.store,source.lesson.id,{token:remote.token},source.actor);const upload=await beginUpload(dest.store,{bytes:bytes.length,sha256:sha256(bytes)},dest.actor);for(let n=0;n<upload.chunks;n++)await writeChunk(dest.store,upload.id,n,bytes.subarray(n*upload.chunkBytes,(n+1)*upload.chunkBytes),dest.actor);const review=await previewTransfer(dest.store,upload.id,{targetId:dest.lesson.id},dest.actor);assert.equal(review.canApply,true);assert.ok(review.rows[0].warnings.some(w=>w.includes('brouillon')));await applyTransfer(dest.store,upload.id,{token:review.token,confirmed:true},dest.actor);const reloaded=await load(dest);assert.equal(reloaded.spec.title,'Contenu importé');assert.equal(reloaded.hasPublishedDraft,false);assert.ok(await dest.store.get('lesson_versions',retired));await assert.rejects(()=>save(dest,draft),e=>e.status===409);
 }finally{await close(source,dest);}});
