import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openStore} from '../server/store.mjs';
import {proposePlanOperations,applyPlanOperations} from '../server/planning.mjs';
import {interpretIntent} from '../server/intent.mjs';
import {calculateRemediation,adjustRemediation,stabilizeRemediation,recordObservation} from '../server/remediation.mjs';
import {runPublicationJob} from '../server/jobs.mjs';
import {storeArtifact,artifactBuffer} from '../server/artifacts.mjs';
const actor={id:'t',classId:'A1',role:'teacher'};
const entry=(id,date,skills=['C1'])=>({id,classId:'A1',date,objective:id,skills,sequence:'S01',module:'Web',activity:'Pratique',duration:175,durationConfirmed:true,status:'planned',resourcePack:id});
async function fixture(){const s=await openStore({path:':memory:',url:''});for(const c of ['C1','C2'])await s.insert('competency_n3',{id:c,classId:'A1',n3_code:c,prerequisiteCodes:c==='C2'?['C1']:[]});for(const e of [entry('a','2026-10-05'),entry('b','2026-10-08',['C2'])])await s.insert('plan_entries',e);await s.insert('plan_versions',{id:'p',classId:'A1',version:1,entries:await s.list('plan_entries','A1')});await s.insert('learners',{id:'l',classId:'A1'});return s;}
test('split and merge are reviewable atomic versions; historical sources retained',async()=>{const s=await fixture();try{const original=await s.get('plan_entries','a'),p=await proposePlanOperations(s,actor,{reason:'Scinder',operations:[{type:'split',entryId:'a',parts:[{...original,date:'2026-10-05',duration:90},{...original,date:'2026-10-06',duration:85}]}]});assert.equal((await s.list('plan_entries','A1')).length,2);assert.equal(p.changes.length,3);await applyPlanOperations(s,p.id,actor,{confirmed:true});const parts=(await s.list('plan_entries','A1')).filter(e=>e.parentEntryIds?.includes('a'));assert.equal(parts.length,2);assert.equal((await s.get('plan_entries','a')).status,'replaced');const m=await proposePlanOperations(s,actor,{reason:'Fusionner',operations:[{type:'merge',entryIds:parts.map(e=>e.id),entry:{date:'2026-10-07',objective:'Réunir',duration:175,durationConfirmed:true}}]});await applyPlanOperations(s,m.id,actor,{confirmed:true});assert.equal((await s.list('plan_versions','A1')).length,3);assert.equal((await s.list('plan_versions','A1'))[0].entries[0].status,'planned');}finally{await s.close();}});
test('invalid batch rolls back; cross-class IDs and invalid dates rejected',async()=>{const s=await fixture();try{for(const operations of [[{type:'move',entryId:'a',date:'2026-02-30'}],[{type:'update',entryId:'a',patch:{status:'completed'}}],[{type:'insert',entry:{date:'2026-10-07',objective:'New',skills:['unknown']}}],[{type:'move',entryId:'a',date:'2026-10-06'},{type:'move',entryId:'other-class',date:'2026-10-07'}]])await assert.rejects(proposePlanOperations(s,actor,{reason:'Test',operations}));assert.equal((await s.get('plan_entries','a')).date,'2026-10-05');assert.equal((await s.list('plan_changes','A1')).length,0);}finally{await s.close();}});
test('concurrent approvals accept only one base version',async()=>{const s=await fixture();try{const a=await proposePlanOperations(s,actor,{reason:'A',operations:[{type:'swap',entryId:'a',otherEntryId:'b'}]}),b=await proposePlanOperations(s,actor,{reason:'B',operations:[{type:'postpone',entryId:'a'}]});const results=await Promise.allSettled([applyPlanOperations(s,a.id,actor,{confirmed:true}),applyPlanOperations(s,b.id,actor,{confirmed:true})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await s.list('plan_versions','A1')).length,2);}finally{await s.close();}});
test('unplanned intent returns a draft without silently inserting; ambiguous dates request choice',async()=>{const s=await fixture();try{const r=await interpretIntent(s,actor,{intent:'Prépare le 2026-10-09'});assert.equal(r.kind,'unplanned_draft');assert.equal((await s.list('plan_entries','A1')).length,2);await s.insert('plan_entries',entry('c','2026-10-05'));assert.equal((await interpretIntent(s,actor,{intent:'Prépare le 2026-10-05'})).kind,'clarification');}finally{await s.close();}});
test('criterion adjustments preserve unrelated memberships and survive recalculation',async()=>{const s=await fixture();try{for(const [criterion,level] of [['C1','NA'],['C2','A2']])await s.insert('evidence',{id:criterion,classId:'A1',learnerId:'l',criterion,sourceId:criterion,date:'2026-10-01',level,approved:true});const r=await calculateRemediation(s,actor,{date:'2026-10-05'});const adjusted=await adjustRemediation(s,actor,{version:r.version,learnerId:'l',criteria:['C1'],group:'G1',reason:'Accompagnement'});assert.deepEqual(adjusted.groups.find(g=>g.id==='G3').members[0].criteria,['C2']);const next=await calculateRemediation(s,actor,{date:'2026-10-06'});assert.deepEqual(next.groups.find(g=>g.id==='G1').members[0].criteria,['C1']);assert.equal(next.summary.find(g=>g.group==='G0').count,0);assert.equal(next.sourceEvidenceIds.length,2);}finally{await s.close();}});
test('weekly stabilization preserves groups but refreshes proof metrics; next week reconsiders',async()=>{const s=await fixture();try{await s.insert('evidence',{id:'first',classId:'A1',learnerId:'l',criterion:'C1',sourceId:'first',date:'2026-10-05',level:'NA',approved:true});const first=await calculateRemediation(s,actor,{date:'2026-10-05'});await stabilizeRemediation(s,actor,{confirmed:true,version:first.version});for(let i=0;i<4;i++)await s.insert('evidence',{id:'new'+i,classId:'A1',learnerId:'l',criterion:'C1',sourceId:'new'+i,date:'2026-10-06',level:'A2',approved:true});const same=await calculateRemediation(s,actor,{date:'2026-10-07'});assert.equal(same.groups.find(g=>g.id==='G0').members[0].metrics.C1.proofCount,5);const next=await calculateRemediation(s,actor,{date:'2026-10-12'});assert.equal(next.groups.find(g=>g.id==='G0').members.length,0);}finally{await s.close();}});
test('teacher observation informs grouping but creates no mastery evidence',async()=>{const s=await fixture();try{await recordObservation(s,actor,{learnerId:'l',criterion:'C1',date:'2026-01-01',level:'EC',note:'A besoin d’un exemple'});const r=await calculateRemediation(s,actor,{date:'2026-10-05'});assert.equal(r.groups.find(g=>g.id==='G1').members.length,1);assert.equal((await s.list('evidence','A1')).length,0);assert.equal(r.sourceObservationIds.length,1);}finally{await s.close();}});
test('durable jobs are claimed once and expired leases resume with frozen version',async()=>{const s=await fixture();try{await s.insert('lessons',{id:'lesson',classId:'A1',versionId:'v1'});await s.insert('publication_jobs',{id:'job',classId:'A1',lessonId:'lesson',lessonVersionId:'v1',actor,spec:{},status:'queued',attempts:0,availableAt:'2026-01-01'});let calls=0;const publish=async()=>{calls++;return {id:'report',status:'success'};};await Promise.all([runPublicationJob(s,{publish}),runPublicationJob(s,{publish})]);assert.equal(calls,1);assert.equal((await s.get('publication_jobs','job')).status,'completed');await s.insert('publication_jobs',{id:'expired',classId:'A1',lessonId:'lesson',lessonVersionId:'wrong-version',actor,spec:{},status:'running',leaseUntil:'2026-01-01',attempts:2});const result=await runPublicationJob(s,{publish});assert.equal(result.status,'failed');assert.equal(calls,1);}finally{await s.close();}});
test('content-addressed artifacts deduplicate and verify bytes without unsafe paths',async()=>{const path=await mkdtemp(join(tmpdir(),'eden-artifacts-')),old=process.env.EDEN_ARTIFACT_PATH;process.env.EDEN_ARTIFACT_PATH=path;try{const a=await storeArtifact(Buffer.from('safe')),b=await storeArtifact(Buffer.from('safe'));assert.equal(a.artifactKey,b.artifactKey);assert.equal((await artifactBuffer(a)).toString(),'safe');await assert.rejects(artifactBuffer({...a,artifactKey:'../../etc/passwd'}));}finally{if(old===undefined)delete process.env.EDEN_ARTIFACT_PATH;else process.env.EDEN_ARTIFACT_PATH=old;await rm(path,{recursive:true});}});

import {reconcileImport} from '../server/reconciliation.mjs';
import {saveLearningEvent} from '../server/progress.mjs';
import {proposeAdaptation,applyAdaptation} from '../server/adaptation.mjs';
test('historical reconciliation is explicit, idempotent and does not infer autonomy',async()=>{const s=await fixture();try{await s.insert('imports',{id:'import',classId:'A1',sha256:'hash',status:'applied',parsed:{history:[{date:'2026-01-01',assessmentId:'eval',learner:'Learner',criteria:[{criterion:'C1',levelValue:3}]}],journal:[{date:'2026-01-01',skills:['C1'],trace:'source'}]}});const input={kind:'assessment',index:0,confirmed:true,reason:'Relu',learnerId:'l',criteria:[{criterion:'C1',level:'A2'}]};await reconcileImport(s,'import',actor,input);await reconcileImport(s,'import',actor,input);const proofs=await s.list('evidence','A1');assert.equal(proofs.length,1);assert.equal(proofs[0].autonomous,false);assert.equal(proofs[0].transfer,false);await assert.rejects(reconcileImport(s,'import',actor,{kind:'journal',index:0,confirmed:true,reason:'Relu',status:'completed',coveredSkills:['C2'],coveredContent:'wrong criterion'}));await reconcileImport(s,'import',actor,{kind:'journal',index:0,confirmed:true,reason:'Relu',status:'not_completed'});assert.equal((await s.list('lesson_runs','A1'))[0].eligibleForDiagnostic,false);}finally{await s.close();}});
test('learning progress is identity-bound, durable and event-idempotent',async()=>{const s=await fixture();try{await s.insert('lessons',{id:'lesson',classId:'A1',status:'published',versionId:'v1'});await s.insert('lesson_versions',{id:'v1',classId:'A1',spec:{activities:[{id:'task'}],blocks:[]}});const learner={id:'l',classId:'A1'},event={lessonId:'lesson',eventId:'one',activityId:'task',type:'answer_saved',payload:{answer:'Original'}};await saveLearningEvent(s,learner,event);await saveLearningEvent(s,learner,{...event,payload:{answer:'Changed'}});assert.equal((await s.get('learning_progress','l:v1')).answers.task,'Original');assert.equal((await s.list('learning_events','A1')).length,1);await assert.rejects(saveLearningEvent(s,{id:'other',classId:'B'},event));}finally{await s.close();}});

import {seedCatalog,worldAccess} from '../server/game.mjs';
test('world overrides open access without creating mastery evidence',async()=>{const s=await fixture();try{await seedCatalog(s);const learner={id:'l',classId:'A1'};assert.equal((await worldAccess(s,learner,'bunker')).unlocked,false);await s.insert('game_teacher_overrides',{id:'o',classId:'A1',learnerId:'l',worldId:'bunker',enabled:true});assert.equal((await worldAccess(s,learner,'bunker')).unlocked,true);assert.equal((await s.list('evidence','A1')).length,0);assert.equal((await worldAccess(s,{id:'other',classId:'A1'},'bunker')).unlocked,false);}finally{await s.close();}});
