"""Parcours réel navigateur. Exécuter après npm start (ou EDEN_TEST_URL).
Le script ne change aucune politique de sécurité du navigateur.
"""
from pathlib import Path
import json, os
from playwright.sync_api import sync_playwright, expect

OUT = Path(os.getenv('EDEN_TEST_OUTPUT', 'test-results'))

def exercise(page, capture=True):
    OUT.mkdir(parents=True, exist_ok=True)
    visited=[]
    def shot(name):
        if capture:
            page.wait_for_timeout(230)
            page.screenshot(path=str(OUT/f'{name}.png'), full_page=True)
    def nxt(expected):
        page.locator('#next-button').click()
        expect(page).to_have_url(__import__('re').compile('#'+expected+'$'))
        visited.append(expected)
    def fill(id,text):page.locator('#'+id).fill(text)
    def action(name, value=None):
        sel=f'[data-action="{name}"]'
        if value is not None:sel+=f'[data-value="{value}"]'
        page.locator(sel).first.click()
    shot('01_accueil')
    fill('alias','Alex test')
    action('start')
    # Un écran incomplet ne passe pas.
    page.locator('#next-button').click()
    expect(page.locator('#step-feedback')).to_contain_text('Choisis une réponse')
    for k,v in {'d_cpu':'M','d_ssd':'M','d_keyboard':'M','d_editor':'L','d_browser':'L','d_ubuntu':'L'}.items():
        page.locator('#'+k).select_option(v)
    nxt('diag-roles')
    for k,v in {'d_exec':'CPU','d_store':'SSD','d_ram':'RAM'}.items():page.locator('#'+k).select_option(v)
    nxt('diag-fichier')
    fill('d_version','La version déjà enregistrée.')
    fill('d_why','Les dernières modifications ne sont pas sauvegardées.')
    nxt('diag-html')
    fill('d_tool','VS Code')
    fill('d_actions','Enregistrer le fichier puis recharger le navigateur.')
    nxt('correction')
    nxt('boot-observe')
    shot('02_schema_demarrage')
    nxt('boot-game')
    # Cas négatif : une carte seule ne passe pas.
    action('boot-add','power')
    action('boot-check')
    expect(page.locator('#game-feedback')).to_contain_text('Regarde les relais')
    for x in ['firmware','loader','kernel','session']:action('boot-add',x)
    action('boot-check')
    shot('03_jeu_demarrage')
    nxt('boot-explain')
    fill('m1_relay','Le chargeur lance le noyau.')
    fill('m1_intruder','VS Code est une application non nécessaire au démarrage.')
    nxt('boot-transfer')
    fill('m1_transfer','Je demanderais quel message apparaît à l’écran.')
    nxt('process-observe')
    action('sample')
    expect(page.locator('#m2_source')).to_have_value('simule')
    nxt('counter-predict')
    for _ in range(3):action('counter-plus')
    page.locator('#m2_prediction').select_option('zero')
    action('counter-reload')
    expect(page.locator('#counter-score')).to_have_text('0')
    nxt('counter-compare')
    fill('m2_observation','Le compteur repart à zéro ; le fichier témoin reste enregistré.')
    nxt('process-zero')
    action('choice','waiting')
    nxt('ancrage')
    fill('anchor_boot','Lancer le noyau.')
    fill('anchor_process','Un programme en cours d’exécution.')
    nxt('pause')
    action('pause-start')
    expect(page.locator('#pause-clock')).to_have_text('15:00')
    shot('04_pause')
    nxt('os-intro')
    nxt('os-ram')
    for x in ['browser','music','editor','game']:action('toggle-app',x)
    expect(page.locator('#game-feedback')).to_contain_text('Il faudrait 10 cases')
    action('toggle-app','editor')
    action('toggle-app','game')
    expect(page.locator('.ram-caption')).to_contain_text('8 / 8')
    shot('05_jeu_ram')
    nxt('os-cpu')
    for x in ['browser','music','game','browser','music','game']:action('cpu-turn',x)
    shot('06_jeu_cpu')
    nxt('os-explain')
    fill('m3_explanation','La RAM fournit de la place ; le CPU donne du temps de calcul.')
    nxt('file-observe')
    nxt('file-allow')
    for x in ['app','services','kernel','driver','disk']:action('relay-add',x)
    action('relay-check')
    nxt('file-deny')
    action('choice','deny')
    action('rights-check')
    expect(page.locator('.flow-node.blocked')).to_contain_text('refus')
    shot('07_droits')
    nxt('file-explain')
    fill('m4_decision','Projets autorise la modification ; Bulletins est en lecture seule pour protéger les données.')
    nxt('code-predict')
    action('choice','continue')
    nxt('code-experience')
    action('editor-close')
    action('editor-plus')
    fill('m5_observation','Le bouton fonctionne encore : la page est déjà chargée.')
    shot('08_editeur')
    nxt('code-roles')
    for k,v in {'role_edit':'editor','role_engine':'engine','role_os':'os','role_cpu':'cpu'}.items():page.locator('#'+k).select_option(v)
    nxt('code-zoom')
    nxt('incident-a')
    action('choice','entries')
    fill('m6_a_reason','Les entrées ne sont pas fournies, même si le SSD est détecté.')
    nxt('incident-b')
    action('choice','process')
    fill('m6_b_reason','La Calculatrice et les autres fenêtres répondent.')
    nxt('incident-code')
    action('run-code')
    expect(page.locator('#console-output')).to_contain_text('socre',timeout=5000)
    shot('09_erreur_code')
    code=page.locator('#code-editor').input_value().replace('socre','score')
    fill('code-editor',code)
    action('run-code')
    expect(page.locator('#code-output')).to_have_text('Score : 3',timeout=5000)
    expect(page.locator('#code-status')).to_contain_text('Correction testée')
    fill('m6_c_reason','J’ai lu ReferenceError, corrigé socre en score, puis obtenu Score : 3 sans cette erreur.')
    shot('10_code_corrige')
    nxt('bilan')
    fill('bilan','J’ai vu une erreur de nom. J’ai corrigé puis exécuté. J’ai vérifié Score : 3.')
    nxt('ticket-1')
    # Le mémo n’est pas disponible pendant le ticket.
    action('notebook')
    expect(page.locator('#toast')).to_contain_text('sans le mémo')
    fill('t1','Le firmware commence ; le chargeur lance le noyau.')
    nxt('ticket-2')
    fill('t2','L’OS gère la mémoire et le temps CPU.')
    nxt('ticket-3')
    fill('t3','Le moteur JavaScript du navigateur.')
    nxt('ticket-4')
    fill('t4','Je lis la console de la page car le reste du système fonctionne.')
    nxt('fin')
    expect(page.locator('.report-progress')).to_contain_text('6/6')
    shot('11_bilan')
    action('report')
    expect(page.locator('#modal')).to_be_visible()
    expect(page.locator('#modal')).to_contain_text('ReferenceError')
    action('close-modal')
    return visited

def main():
    base=os.getenv('EDEN_TEST_URL','http://127.0.0.1:4173/')
    executable=os.getenv('EDEN_CHROMIUM')
    with sync_playwright() as p:
        launch={'headless':True}
        if executable:launch['executable_path']=executable
        browser=p.chromium.launch(**launch)
        context=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True)
        page=context.new_page()
        errors=[];page.on('pageerror',lambda er:errors.append(str(er)))
        page.goto(base,wait_until='domcontentloaded')
        page.locator('#alias').wait_for()
        visited=exercise(page)
        # Export réel et reprise native : à exécuter sur un navigateur autorisé.
        with page.expect_download() as dl:
            page.locator('[data-action="export-html"]').first.click()
        path=OUT/'bilan.html';dl.value.save_as(path)
        assert 'Score : ' in path.read_text()
        page.reload(wait_until='domcontentloaded')
        expect(page.locator('#step-title')).to_have_text('Tu sais mieux où regarder.')
        assert not errors, errors
        # Mobile : écran déjà atteint, sans débordement horizontal.
        page.set_viewport_size({'width':390,'height':844})
        page.wait_for_timeout(250)
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth + 1')
        page.screenshot(path=str(OUT/'12_mobile.png'),full_page=True)
        (OUT/'resultats.json').write_text(json.dumps({'visited':visited,'native_reload':True,'download':True,'errors':errors},ensure_ascii=False,indent=2))
        browser.close()
    print(f'Parcours de bout en bout terminé. Résultats dans {OUT}.')

if __name__=='__main__':main()
