import test from 'node:test';
import assert from 'node:assert/strict';
import {CHAPTERS,STEPS,BOOT_ORDER,RELAY_ORDER,CODE_START} from '../docs/app/content.js';
import {createState,parseState,validateStep,completeStep,ramUsed,toggleApp,assignCPU,sameOrder,canVisit,minutes,elapsedRemaining,escapeHTML,safeURL,reportHTML,makeReport} from '../docs/app/model.js';
const step=id=>STEPS.find(s=>s.id===id);
function readyRam(){let g=createState().game;for(const id of ['browser','music','editor','game','editor','game'])g=toggleApp(g,id).game;return g;}
test('planning continu : mardi 13h20–16h15',()=>{assert.equal(CHAPTERS[0].start,'13:20');assert.equal(CHAPTERS.at(-1).end,'16:15');for(let i=1;i<CHAPTERS.length;i++)assert.equal(CHAPTERS[i].start,CHAPTERS[i-1].end);});
test('175 minutes dont 15 de pause',()=>{assert.equal(CHAPTERS.reduce((s,c)=>s+minutes(c.end)-minutes(c.start),0),175);const p=CHAPTERS.find(c=>c.id==='pause');assert.equal(p.start,'14:30');assert.equal(p.end,'14:45');});
test('36 identifiants stables et uniques',()=>{assert.equal(STEPS.length,36);assert.equal(new Set(STEPS.map(s=>s.id)).size,36);});
test('nouvel élève : seule la première étape est débloquée',()=>{const s=createState('Alex');assert(canVisit(s,'diag-classer'));assert(!canVisit(s,'incident-code'));assert(!canVisit(s,'absent'));});
test('un diagnostic vide ne passe pas',()=>assert(!validateStep(step('diag-classer'),createState('Alex')).ok));
test('M/L, même une lettre, sont des réponses valides',()=>{const s=createState('Alex');for(const k of ['d_cpu','d_ssd','d_keyboard','d_editor','d_browser','d_ubuntu'])s.answers[k]='M';assert(validateStep(step('diag-classer'),s).ok);});
test('Je ne sais pas est accepté au diagnostic',()=>{const s=createState('Alex');for(const k of ['d_exec','d_store','d_ram'])s.answers[k]='unknown';assert(validateStep(step('diag-roles'),s).ok);});
test('avancer ne modifie pas l’état source',()=>{const s=createState('Alex');s.answers.d_exec=s.answers.d_store=s.answers.d_ram='unknown';const r=completeStep(s,step('diag-roles'));assert(r.verdict.ok);assert.equal(s.completed.length,0);assert(r.state.completed.includes('diag-roles'));});
test('le diagnostic terminé est figé dans le rapport',()=>{const s=createState('Alex');s.answers.d_tool='VS Code';s.answers.d_actions='Enregistrer puis recharger';const {state:n}=completeStep(s,step('diag-html'));n.answers.d_tool='Autre';assert.equal(makeReport(n).answers.find(a=>a.id==='d_tool').value,'VS Code');});
test('démarrage : les 5 cartes dans le bon ordre',()=>{const s=createState('Alex');s.game.boot=[...BOOT_ORDER];assert(!validateStep(step('boot-game'),s).ok);s.game.bootChecked=true;assert(validateStep(step('boot-game'),s).ok);});
test('démarrage : VS Code ne remplace pas le noyau',()=>{assert(!sameOrder(['power','firmware','loader','editor','session'],BOOT_ORDER));});
test('comparaison des ordres tient compte des longueurs',()=>{assert(!sameOrder(['power'],BOOT_ORDER));assert(sameOrder([],[]));});
test('RAM : le triple initial occupe 7 cases',()=>{let g=createState().game;for(const id of ['browser','music','editor'])g=toggleApp(g,id).game;assert.equal(ramUsed(g.open),7);assert(g.ramInitial);});
test('RAM : le refus n’ouvre pas de quatrième application',()=>{let g=createState().game;for(const id of ['browser','music','editor','game'])g=toggleApp(g,id).game;assert.equal(ramUsed(g.open),7);assert(g.ramRefused);assert(!g.open.includes('game'));});
test('RAM : fermeture de deux cases puis ouverture du jeu',()=>{const s=createState('Alex');s.game=readyRam();assert.equal(ramUsed(s.game.open),8);assert(validateStep(step('os-ram'),s).ok);});
test('RAM : ouvrir seulement Jeu ne remplit pas la mission',()=>{const s=createState('Alex');s.game=toggleApp(s.game,'game').game;assert(!validateStep(step('os-ram'),s).ok);});
test('RAM : les identifiants inconnus ne sont pas ajoutés',()=>{const g=createState().game;assert.deepEqual(toggleApp(g,'x').game,g);});
test('CPU : une application fermée ne reçoit aucun tour',()=>{const g=readyRam();assert.equal(assignCPU(g,'editor').cpu.length,0);});
test('CPU : six tours répartis, sans libérer la RAM',()=>{const s=createState('Alex');s.game=readyRam();for(const id of [...s.game.open,...s.game.open])s.game=assignCPU(s.game,id);assert(validateStep(step('os-cpu'),s).ok);assert.equal(ramUsed(s.game.open),8);});
test('CPU : septième tour refusé',()=>{let g=readyRam();for(let i=0;i<7;i++)g=assignCPU(g,'browser');assert.equal(g.cpu.length,6);});
test('CPU : ne pas oublier une application',()=>{const s=createState('Alex');s.game=readyRam();for(let i=0;i<6;i++)s.game=assignCPU(s.game,'browser');assert(!validateStep(step('os-cpu'),s).ok);});
test('changement des apps : efface le planning CPU obsolète',()=>{let g=readyRam();g=assignCPU(g,'browser');g=toggleApp(g,'music').game;assert.equal(g.cpu.length,0);});
test('relais du fichier : ordre complet et testé',()=>{const s=createState('Alex');s.game.relay=[...RELAY_ORDER];s.game.relayChecked=true;assert(validateStep(step('file-allow'),s).ok);});
test('lecture seule : modification refusée et décision testée',()=>{const s=createState('Alex');s.game.rightsChoice='deny';assert(!validateStep(step('file-deny'),s).ok);s.game.rightsChecked=true;assert(validateStep(step('file-deny'),s).ok);});
test('la prédiction seule ne prouve pas l’expérience du compteur',()=>{const s=createState('Alex');s.answers.m2_prediction='zero';assert(!validateStep(step('counter-predict'),s).ok);s.game.counterReloaded=true;assert(validateStep(step('counter-predict'),s).ok);});
test('l’expérience éditeur exige fermeture puis clic',()=>{const s=createState('Alex');s.game.editorClosed=true;s.answers.m5_observation='Le bouton fonctionne.';assert(!validateStep(step('code-experience'),s).ok);s.game.editorClickedClosed=true;assert(validateStep(step('code-experience'),s).ok);});
test('les rôles moteur et CPU sont séparés',()=>{const s=createState('Alex');Object.assign(s.answers,{role_edit:'editor',role_engine:'engine',role_os:'os',role_cpu:'cpu'});assert(validateStep(step('code-roles'),s).ok);s.answers.role_engine='cpu';assert(!validateStep(step('code-roles'),s).ok);});
test('incidents : une réponse choisie doit être justifiée',()=>{const s=createState('Alex');s.answers.m6_a='entries';assert(!validateStep(step('incident-a'),s).ok);s.answers.m6_a_reason='Les entrées ne sont pas fournies.';assert(validateStep(step('incident-a'),s).ok);});
test('code : un texte modifié doit être retesté',()=>{const s=createState('Alex');s.game.codeSawError=true;s.game.codePassed=true;s.game.codeLastTested=s.game.code;s.answers.m6_c_reason='Erreur relevée puis corrigée et testée.';assert(validateStep(step('incident-code'),s).ok);s.game.code+=' ';assert(!validateStep(step('incident-code'),s).ok);});
test('round trip de sauvegarde',()=>{const s=createState('Alex');s.game=readyRam();s.answers.m3_explanation='Une place et un temps.';const r=parseState(JSON.stringify(s));assert.equal(r.alias,'Alex');assert.deepEqual(r.game.open,s.game.open);assert.equal(r.answers.m3_explanation,s.answers.m3_explanation);});
test('autre séance : import rejeté',()=>{const s=createState('Alex');s.sessionId='autre';assert.throws(()=>parseState(JSON.stringify(s)),/autre séance/);});
test('JSON malformé : rejet explicite',()=>assert.throws(()=>parseState('{boom'),/JSON valide/));
test('import trop grand : rejet explicite',()=>assert.throws(()=>parseState('x'.repeat(250001)),/volumineux/));
test('normalisation : bornes et chemins',()=>{const s=createState('Alex');s.maxVisited=9999;s.current='../secrets';s.game.code='x'.repeat(9000);s.game.open=['browser','music','editor','game'];const n=parseState(JSON.stringify(s));assert.equal(n.maxVisited,STEPS.length-1);assert.equal(n.current,STEPS[0].id);assert.equal(n.game.code.length,8000);assert.deepEqual(n.game.open,[]);});
test('clés inconnues ignorées dans les réponses',()=>{const s=createState('Alex');s.answers.script='<script>';const n=parseState(JSON.stringify(s));assert.equal(n.answers.script,undefined);});
test('alias HTML : échappé dans le bilan',()=>{const s=createState('<img src=x onerror=alert(1)>');s.answers.t1='<script>alert(1)</script>';const h=reportHTML(s);assert(!h.includes('<script>'));assert(h.includes('&lt;script&gt;'));assert(!h.includes('<img src=x'));});
test('aucun lien javascript dans la config',()=>{assert.equal(safeURL('javascript:alert(1)'), '');assert.equal(safeURL('data:text/html,x'),'');assert.equal(safeURL(''), '');assert.equal(safeURL('https://school.example/rendu'),'https://school.example/rendu');});
test('escapeHTML traite tous les délimiteurs',()=>assert.equal(escapeHTML(`<>&"'`),'&lt;&gt;&amp;&quot;&#39;'));
test('minuteur : n’expire pas à une valeur négative',()=>{assert.equal(elapsedRemaining(1000,20,1_201_001),0);assert.equal(elapsedRemaining(null,15),900);});
test('fiche finale à la fin seulement dans la progression',()=>{const s=createState('Alex');assert(!canVisit(s,'fin'));s.maxVisited=STEPS.length-1;assert(canVisit(s,'fin'));});
test('le rapport n’affirme ni note ni envoi automatique',()=>{const r=makeReport(createState('Alex'));assert(r.note.includes('Aucun envoi automatique'));assert.equal(r.session.start,'13:20');assert(r.answers.length>30);});
