import {labRoutes} from './pedagogy/labs.mjs';
import {visualRoutes} from './pedagogy/visuals.mjs';
import {domRoutes} from './pedagogy/dom.mjs';
import {pedagogyRoutes} from './pedagogy/routes.mjs';
import {enqueueGeneration,jobSummary,qualityEnabled} from './pedagogy/jobs.mjs';
import {arcadeRoutes,arcadeEnabled} from './arcade.mjs';
import {adaptMission,validateMission,assignMission} from './mission-authoring.mjs';
import {retrieveResources} from './retrieval.mjs';
import {saveLearningEvent} from './progress.mjs';
import {reconciliationPreview,reconcileImport} from './reconciliation.mjs';
import {enqueueDrive,retryPublicationJob,runPublicationJob} from './jobs.mjs';
import {streamCorpus} from './artifacts.mjs';
import express from 'express';
import {proposeAdaptation,applyAdaptation} from './adaptation.mjs';
import {adjustRemediation,stabilizeRemediation,recordObservation} from './remediation.mjs';
import {interpretIntent} from './intent.mjs';
import {readFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomBytes,timingSafeEqual} from 'node:crypto';
import {uid,now,fail,requireValue,scoped} from './store.mjs';
import {authentication,loggedIn,teacher,student,protectOrigin,limitLogin,passwordHash,passwordMatches,safeUser,createSession,cookie,replacePassword} from './auth.mjs';
import {previewImport,applyImport,hash} from './importer.mjs';
import {generateLesson,studentSpec,parisDate,library} from './generator.mjs';
import {lessonQuality,publishLesson,closeLesson,editLesson,proposePlanChange,applyPlanChange} from './domain.mjs';
import {preparePublication,takeOverDraft} from './publication-readiness.mjs';
import {proposeLessonRevision,applyLessonRevision} from './lesson-revision.mjs';
import {submitAttempt,reviseCorrection,proposeRubricCorrection,computeRemediation,mastery} from './assessment.mjs';
import {compileCorpus,zipFiles,individualExport,workbook,downloadableCorpus} from './corpus.mjs';
import {catalog,startGame,recordGameEvent,worldAccess,authorizeRun} from './game.mjs';
import {driveConfigured,getDrive,listStudents,listChildFolders,publishDrive} from './drive.mjs';
import {runSafe} from './safe-js.mjs';
import {testActivityCode} from './workshop-testing.mjs';
import {reviseDiagnostic} from './diagnostic-revision.mjs';
import {demoRoutes} from './demo-routes.mjs';
import {databaseRoutes} from './database-routes.mjs';
import {aiRoutes} from './ai/routes.mjs';
import {workSubmissionRoutes} from './work-submissions.mjs';
export function createApp(store,{chatgpt,lessonRevision={}}={}){
 const app=express();app.disable('x-powered-by');
 app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',req.path.startsWith('/game/')?"default-src 'none'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src data:; worker-src blob:; connect-src 'none'; frame-ancestors 'self'":"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'self'");next();});
 app.use(protectOrigin,authentication(store));app.use(express.json({limit:'2mb'}));
 databaseRoutes(app,store);
 demoRoutes(app);
 arcadeRoutes(app,store);
 aiRoutes(app,store,{chatgpt});
 pedagogyRoutes(app,store,{chatgpt});
 labRoutes(app,store);
 visualRoutes(app,store);
 domRoutes(app,store);
 workSubmissionRoutes(app,store);
 app.get('/api/internal/publication-worker',async(req,res)=>{const expected=process.env.CRON_SECRET?Buffer.from('Bearer '+process.env.CRON_SECRET):null,provided=Buffer.from(req.headers.authorization||'');if(!expected||provided.length!==expected.length||!timingSafeEqual(provided,expected))fail(401,'Accès worker refusé.');const job=await runPublicationJob(store);res.json({processed:!!job,jobId:job?.id,status:job?.status});});
 app.get('/api/health',(req,res)=>res.json({ok:true,service:'EDEN Teacher Twin',storage:store.kind}));
 app.get('/api/session',async(req,res)=>res.json({user:req.user?safeUser(req.user):null,setupRequired:!(await store.list('teachers')).length,worldArcadeEnabled:arcadeEnabled(),date:parisDate()}));
 app.post('/api/setup',limitLogin,async(req,res)=>{if(process.env.NODE_ENV==='production')fail(403,'Configurez EDEN_TEACHER_PASSWORD côté serveur.');if(!['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress))fail(403,'Initialisation locale uniquement.');const input=req.body;requireValue(typeof input.password==='string'&&input.password.length>=12,'Mot de passe : au moins 12 caractères.');const user=await store.transaction(async tx=>{if((await tx.list('teachers')).length)fail(409,'Installation déjà initialisée.');return tx.insert('teachers',{id:uid('teacher'),classId:'A1',role:'teacher',displayName:'Professeur',username:'professeur',passwordHash:passwordHash(input.password)});});res.json({user:await createSession(store,user,res)});});
 app.post('/api/login',limitLogin,async(req,res)=>{requireValue(['teacher','student'].includes(req.body.role),'Rôle invalide.');const role=req.body.role;const result=await store.transaction(async tx=>{const user=(await tx.list(role==='teacher'?'teachers':'learners')).find(u=>u.username===req.body.username&&u.classId===(req.body.classId||'A1'));if(!user||!passwordMatches(req.body.password,user.passwordHash))fail(401,'Identifiants incorrects.');return createSession(tx,{...user,role},res);});res.json({user:result});});
 app.post('/api/logout',loggedIn,async(req,res)=>{if(req.sessionId)await store.remove('sessions',req.sessionId);cookie(res,'');res.json({ok:true});});
 app.get('/api/dashboard',teacher,async(req,res)=>{const tables=['plan_entries','plan_versions','lessons','lesson_runs','learners','corrections','remediation_snapshots','competency_n3','evidence','imports','game_evidence'];const values=await Promise.all(tables.map(t=>store.list(t,req.user.classId)));const data=Object.fromEntries(tables.map((t,i)=>[t,values[i]]));res.json({date:parisDate(),entries:data.plan_entries,planVersion:data.plan_versions.at(-1)?.version||0,lessons:data.lessons,runs:data.lesson_runs,learners:data.learners.map(l=>({...safeUser(l),hasAccess:!!l.passwordHash,driveFolderId:l.driveFolderId||null})),corrections:data.corrections,remediation:data.remediation_snapshots.at(-1)||null,criteria:data.competency_n3,evidence:data.evidence,gameEvidence:data.game_evidence,imports:data.imports.map(({parsed,...r})=>r),integrations:{openai:!!(process.env.OPENAI_API_KEY&&process.env.OPENAI_MODEL),drive:driveConfigured(),storage:store.kind}});});
 const reportSummary=report=>{const {parsed,...summary}=report;return {...summary,counts:parsed?{criteria:parsed.criteria.length,entries:parsed.entries.length,sequences:parsed.sequences.length,learners:parsed.learners.length}:null};};
 app.post('/api/imports/planning',teacher,express.raw({type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',limit:'20mb'}),async(req,res)=>{requireValue(Buffer.isBuffer(req.body),'Envoyez le fichier XLSX avec son type MIME.');res.json(reportSummary(await previewImport(store,req.body,req.user)));});
 app.post('/api/imports/planning/source',teacher,async(req,res)=>{const file=(await readdir('.')).find(n=>n.startsWith('Planification_A1_')&&n.endsWith('.xlsx'));requireValue(file,'Classeur source absent. Importez un fichier.');res.json(reportSummary(await previewImport(store,await readFile(file),req.user)));});
 app.post('/api/imports/:id/apply',teacher,async(req,res)=>res.json(reportSummary(await applyImport(store,req.params.id,req.user,req.body))));
 app.get('/api/imports/:id/reconciliation',teacher,async(req,res)=>res.json(await reconciliationPreview(store,req.params.id,req.user)));
 app.post('/api/imports/:id/reconciliation',teacher,async(req,res)=>res.json(await reconcileImport(store,req.params.id,req.user,req.body)));
 app.get('/api/curricula/:id',teacher,async(req,res)=>res.json(await scoped(store,'curriculum_versions',req.params.id,req.user)));
 app.get('/api/plans/:id',teacher,async(req,res)=>{if(req.params.id!==req.user.classId)fail(404,'Classe inconnue.');res.json({entries:await store.list('plan_entries',req.user.classId),version:(await store.list('plan_versions',req.user.classId)).at(-1)});});
 app.get('/api/plans/:id/versions',teacher,async(req,res)=>{if(req.params.id!==req.user.classId)fail(404,'Classe inconnue.');res.json(await store.list('plan_versions',req.user.classId));});
 app.post('/api/plans/:id/changes/propose',teacher,async(req,res)=>res.json(await proposePlanChange(store,req.user,req.body)));
 app.patch('/api/plans/:id/entries/:entryId',teacher,async(req,res)=>res.json(await proposePlanChange(store,req.user,{...req.body,entryId:req.params.entryId})));
 app.post('/api/plans/:id/changes/:changeId/apply',teacher,async(req,res)=>res.json(await applyPlanChange(store,req.params.changeId,req.user,req.body)));
 const generate=async(req,res)=>{requireValue(typeof req.body.intent==='string'&&req.body.intent.length<=4000,'Intention attendue (4000 caractères maximum).');if(req.body.mode==='change_plan')return res.json(await proposePlanChange(store,req.user,req.body));if(qualityEnabled()&&req.body.localOnly!==true)return res.status(202).json({kind:'preparation_job',job:jobSummary(await enqueueGeneration(store,req.user,req.body,{chatgpt}))});const result=await generateLesson(store,{classId:req.user.classId,intent:req.body.intent,targetDate:req.body.targetDate||null,constraints:req.body.constraints||[],mode:req.body.mode||'prepare'},req.user,{entryId:req.body.entryId,localOnly:req.body.localOnly===true});const corpus=await compileCorpus(store,result.id,req.user);const {quality}=await lessonQuality(store,result);result.quality=quality;await store.put('lessons',{...result,spec:undefined});res.json({...result,corpusManifest:corpus.manifest,bundle:{lesson:result.spec,diagnostic:result.spec.diagnostic,rubric:result.spec.diagnostic.rubric,correctionReference:result.spec.diagnostic.tasks.map(t=>({id:t.id,reference:t.reference})),remediationPolicy:{groups:['G0','G1','G2','G3'],unobserved:'NE'},codeStationMission:result.spec.codeStation,teacherGuide:result.spec.teacherGuide,studentInterface:studentSpec(result.spec),corpusManifest:corpus.manifest,journalDraft:{coveredSkills:[],status:'planned'},qualityReport:quality,planImpact:null}});};
 app.post('/api/twin/intent',teacher,async(req,res)=>{const result=await interpretIntent(store,req.user,req.body);if(result.kind!=='prepare')return res.json(result);req.body={...req.body,entryId:result.entryId,mode:result.mode};return generate(req,res);});app.post('/api/lessons/generate',teacher,generate);
 app.get('/api/twin/runs/:id',teacher,async(req,res)=>res.json(await scoped(store,'agent_runs',req.params.id,req.user)));
 app.post('/api/twin/runs/:id/approve',teacher,async(req,res)=>{const run=await scoped(store,'agent_runs',req.params.id,req.user);res.json(await publishLesson(store,run.lessonId,req.user,req.body));});
 app.get('/api/lessons/:id',teacher,async(req,res)=>{const lesson=await scoped(store,'lessons',req.params.id,req.user);const {quality,version,pack}=await lessonQuality(store,lesson);res.json({...lesson,quality,spec:version.spec,corpusManifest:pack?.manifest||null});});
 app.put('/api/lessons/:id',teacher,async(req,res)=>res.json(await editLesson(store,req.params.id,req.body,req.user)));
 app.post('/api/lessons/:id/revisions/propose',teacher,async(req,res)=>res.json(await proposeLessonRevision(store,req.params.id,req.body||{},req.user,{...lessonRevision,chatgpt})));
 app.post('/api/lessons/:id/revisions/apply',teacher,async(req,res)=>res.json(await applyLessonRevision(store,req.params.id,req.body||{},req.user)));
 app.get('/api/lessons/:id/revisions',teacher,async(req,res)=>{await scoped(store,'lessons',req.params.id,req.user);res.json((await store.list('lesson_adaptations',req.user.classId)).filter(p=>p.kind==='prompt_revision'&&p.lessonId===req.params.id&&p.actorId===req.user.id).map(({trace,requestHash,...p})=>p));});
 app.post('/api/lessons/:id/take-over',teacher,async(req,res)=>res.json(await takeOverDraft(store,req.params.id,req.body||{},req.user)));
 app.post('/api/lessons/:id/diagnostic/revise',teacher,async(req,res)=>res.json(await reviseDiagnostic(store,req.params.id,req.body||{},req.user)));
 app.post('/api/lessons/:id/adapt/propose',teacher,async(req,res)=>res.json(await proposeAdaptation(store,req.params.id,req.user,req.body)));
 app.post('/api/lessons/:id/adapt/apply',teacher,async(req,res)=>{const lesson=await applyAdaptation(store,req.params.id,req.user,req.body);await compileCorpus(store,lesson.id,req.user);res.json(lesson);});
 app.post('/api/lessons/:id/preview',teacher,async(req,res)=>{const lesson=await scoped(store,'lessons',req.params.id,req.user);requireValue(!req.body?.lessonVersionId||req.body.lessonVersionId===lesson.versionId,'La version de la séance a changé. Rechargez-la avant de l’essayer.');res.json(studentSpec((await store.get('lesson_versions',lesson.versionId)).spec));});
 app.post('/api/lessons/:id/preview/test',teacher,async(req,res)=>{
  const lesson=await scoped(store,'lessons',req.params.id,req.user);requireValue(req.body?.lessonVersionId===lesson.versionId,'La version de la séance a changé. Rechargez l’aperçu.');
  const spec=(await scoped(store,'lesson_versions',lesson.versionId,req.user)).spec,task=[...spec.activities,...spec.diagnostic.tasks].find(a=>a.id===req.body.taskId&&['CodeEditor','TestRunner'].includes(a.type));
  requireValue(task&&typeof req.body.code==='string'&&req.body.code.length<=10000,'Exercice et code attendus (10 000 caractères maximum).');
  res.json(await testActivityCode(task,req.body.code));
 });
 app.post('/api/lessons/:id/publication/prepare',teacher,async(req,res)=>res.json(await preparePublication(store,req.params.id,req.body||{},req.user)));
 app.post('/api/lessons/:id/publish',teacher,async(req,res)=>res.json(await publishLesson(store,req.params.id,req.user,req.body)));
 app.post('/api/lessons/:id/close',teacher,async(req,res)=>res.json(await closeLesson(store,req.params.id,req.body,req.user)));
 app.get('/api/today',loggedIn,async(req,res)=>{const date=req.query.date||parisDate(),available=(await store.list('lessons',req.user.classId)).filter(l=>l.status==='published').sort((a,b)=>b.date.localeCompare(a.date)),availableLessons=available.map(({id,title,date})=>({id,title,date})),lesson=req.query.lesson?available.find(l=>l.id===req.query.lesson):available.find(l=>l.date===date);if(req.query.lesson&&!lesson)fail(404,'Séance indisponible pour ta classe.');if(!lesson)return res.json({lesson:null,date,availableLessons});const attempts=(await store.list('assessment_attempts',req.user.classId)).filter(a=>a.lessonVersionId===(lesson.diagnosticVersionId||lesson.versionId)&&a.learnerId===req.user.id),attempt=attempts.at(-1);res.json({lesson:{id:lesson.id,title:lesson.title,date:lesson.date,status:lesson.status,version:lesson.version,versionId:lesson.versionId,runId:lesson.runId,diagnosticVersionId:lesson.diagnosticVersionId,spec:studentSpec((await store.get('lesson_versions',lesson.versionId)).spec,{submitted:!!attempt?.submissionId})},attempt,date:lesson.date,availableLessons,progress:await store.get('learning_progress',`${req.user.id}:${lesson.versionId}`),events:(await store.list('learning_events',req.user.classId)).filter(e=>e.learnerId===req.user.id&&e.lessonRunId===lesson.runId)});});
 app.post('/api/assessments/:id/start',student,async(req,res)=>{const lesson=await scoped(store,'lessons',req.params.id,req.user);requireValue(lesson.status==='published','Séance non ouverte.');res.json(await store.transaction(async tx=>{const existing=(await tx.list('assessment_attempts',req.user.classId)).filter(a=>a.learnerId===req.user.id&&a.lessonVersionId===(lesson.diagnosticVersionId||lesson.versionId)).at(-1);if(existing)return existing;return tx.insert('assessment_attempts',{id:uid('attempt'),classId:req.user.classId,learnerId:req.user.id,lessonId:lesson.id,lessonVersionId:lesson.diagnosticVersionId||lesson.versionId,status:'started',answers:{},history:[],firstAttempt:{},lastAttempt:{},executions:0,hints:0});}));});
 app.post('/api/assessments/:id/save',student,async(req,res)=>res.json(await store.transaction(async tx=>{const a=await scoped(tx,'assessment_attempts',req.params.id,req.user);if(a.learnerId!==req.user.id)fail(403,'Tentative d’un autre élève.');if(a.submissionId)fail(409,'Copie déjà figée.');requireValue(req.body.answers&&typeof req.body.answers==='object','Réponses attendues.');if(JSON.stringify(req.body.answers).length>150000)fail(413,'Copie trop volumineuse.');for(const [taskId,answer] of Object.entries(req.body.answers)){if(answer!==''&&answer!=null){a.firstAttempt[taskId]??={timestamp:now(),type:'answer_saved',payload:{answer}};a.lastAttempt[taskId]={timestamp:now(),type:'answer_saved',payload:{answer}};}}a.answers=req.body.answers;a.savedAt=now();await tx.put('assessment_attempts',a);return {receivedAt:a.savedAt,attemptId:a.id};})));
 app.post('/api/assessments/:id/test',student,async(req,res)=>{const code=req.body.code;requireValue(typeof code==='string'&&code.length<=10000,'Code limité à 10 000 caractères.');res.json(await store.transaction(async tx=>{const a=await scoped(tx,'assessment_attempts',req.params.id,req.user);if(a.learnerId!==req.user.id)fail(403,'Tentative d’un autre élève.');if(a.submissionId)fail(409,'Copie déjà remise.');requireValue(a.history.length<500,'Limite d’essais atteinte.');const spec=(await tx.get('lesson_versions',a.lessonVersionId)).spec,task=spec.diagnostic.tasks.find(t=>t.id===req.body.taskId&&['CodeEditor','TestRunner'].includes(t.type));requireValue(task,'Exercice diagnostique inconnu.');let result;try{result=await testActivityCode(task,code);}catch{result={ok:false,pending:true,status:'technical_incident',logs:['Incident technique : aucun niveau de compétence déduit.'],error:'Exécution indisponible.'};}const event={timestamp:now(),type:'code_run',payload:{taskId:req.body.taskId,code,result}};a.history.push(event);a.firstAttempt[req.body.taskId]??=event;a.lastAttempt[req.body.taskId]=event;a.executions++;await tx.put('assessment_attempts',a);return result;}));});
 app.post('/api/assessments/:id/submit',student,async(req,res)=>{const submission=await submitAttempt(store,req.params.id,req.body.answers,req.user);await computeRemediation(store,req.user);res.json({submissionId:submission.id,sha256:submission.sha256,receivedAt:submission.submittedAt,correction:await store.get('corrections',submission.id)});});
 app.get('/api/assessments/:id/result',student,async(req,res)=>{const a=await scoped(store,'assessment_attempts',req.params.id,req.user);if(a.learnerId!==req.user.id)fail(403,'Tentative d’un autre élève.');res.json(a.submissionId?await store.get('corrections',a.submissionId):{status:'not_submitted',level:'NE'});});
 app.get('/api/teacher/assessments/:id/submissions',teacher,async(req,res)=>res.json((await store.list('submissions',req.user.classId)).filter(s=>s.lessonId===req.params.id)));
 app.get('/api/teacher/submissions/:id',teacher,async(req,res)=>res.json({submission:await scoped(store,'submissions',req.params.id,req.user),correction:await scoped(store,'corrections',req.params.id,req.user)}));
 app.post('/api/teacher/submissions/:id/correction',teacher,async(req,res)=>{const correction=await reviseCorrection(store,req.params.id,req.body,req.user);await computeRemediation(store,req.user);res.json(correction);});
 app.post('/api/teacher/submissions/:id/precorrect',teacher,async(req,res)=>res.json(await proposeRubricCorrection(store,req.params.id,req.user,req.body)));
 app.post('/api/teacher/submissions/:id/reopen',teacher,async(req,res)=>{requireValue(req.body.reason?.trim(),'Justifiez la réouverture.');const s=await scoped(store,'submissions',req.params.id,req.user);res.json(await store.transaction(async tx=>{const current=(await tx.list('assessment_attempts',req.user.classId)).filter(a=>a.learnerId===s.learnerId&&a.lessonVersionId===s.lessonVersionId).at(-1);if(current&&!current.submissionId)return current;const a=await tx.insert('assessment_attempts',{id:uid('attempt'),classId:req.user.classId,learnerId:s.learnerId,lessonId:s.lessonId,lessonVersionId:s.lessonVersionId,status:'reopened',previousSubmissionId:s.id,answers:{},history:[],firstAttempt:{},lastAttempt:{},executions:0,hints:0});await tx.audit(req.user,'assessment.reopened',a.id,{reason:req.body.reason});return a;}));});
 app.get('/api/teacher/submissions/:id/export',teacher,async(req,res)=>{res.type('application/zip').attachment('dossier-eleve.zip').send(await individualExport(store,req.params.id,req.user));});
 app.post('/api/remediation/compute',teacher,async(req,res)=>res.json(await computeRemediation(store,req.user,req.body)));
 app.get('/api/remediation/latest',teacher,async(req,res)=>res.json((await store.list('remediation_snapshots',req.user.classId)).at(-1)||null));
 app.patch('/api/remediation/groups/:id',teacher,async(req,res)=>res.json(await adjustRemediation(store,req.user,{...req.body,group:req.params.id})));
 app.post('/api/remediation/stabilize',teacher,async(req,res)=>res.json(await stabilizeRemediation(store,req.user,req.body)));
 app.post('/api/teacher/observations',teacher,async(req,res)=>res.json(await recordObservation(store,req.user,req.body)));
 app.get('/api/mastery/:id',teacher,async(req,res)=>{await scoped(store,'learners',req.params.id,req.user);const evidence=(await store.list('evidence',req.user.classId)).filter(e=>e.learnerId===req.params.id),policy=(await store.list('teacher_policies',req.user.classId)).at(-1);res.json((await store.list('competency_n3',req.user.classId)).map(c=>({criterion:c.n3_code,...mastery(evidence.filter(e=>e.criterion===c.n3_code),policy)})));});
 app.post('/api/corpus/:id/compile',teacher,async(req,res)=>{const c=await compileCorpus(store,req.params.id,req.user);res.json(c.manifest);});
 app.get('/api/corpus/:id/manifest',teacher,async(req,res)=>{const lesson=await scoped(store,'lessons',req.params.id,req.user),c=(await store.list('corpus_packages',req.user.classId)).find(c=>c.lessonVersionId===lesson.versionId);if(!c)fail(404,'Corpus non compilé.');res.json(c.manifest);});
 app.get('/api/corpus/:id/download',teacher,async(req,res)=>{const lesson=await scoped(store,'lessons',req.params.id,req.user),c=await downloadableCorpus(store,lesson,req.user,req.query.versionId||lesson.versionId);res.type('application/zip').attachment(`${c.manifest.lessonId}_v${c.manifest.lessonVersion}_CORPUS_${c.complete?'COMPLET':'PARTIEL'}.zip`);await streamCorpus(c,res);});
 app.get('/api/resources/search',teacher,async(req,res)=>res.json(await retrieveResources(store,req.user.classId,{query:String(req.query.q||''),criteria:String(req.query.criteria||'').split(',').filter(Boolean)})));
 app.get('/api/resources',teacher,async(req,res)=>{const q=String(req.query.q||'').toLocaleLowerCase();res.json(library.filter(r=>JSON.stringify(r).toLocaleLowerCase().includes(q)));});
 app.post('/api/code/run',student,async(req,res)=>{
  const {code,taskId,lessonId,lessonVersionId}=req.body;requireValue(typeof code==='string'&&code.length<=10000,'Code limité à 10 000 caractères.');
  if(!taskId){const result=runSafe(code);delete result.ast;return res.json(result);}
  const lesson=await scoped(store,'lessons',lessonId,req.user);requireValue(lesson.status==='published','Séance non ouverte.');requireValue(lessonVersionId===lesson.versionId,'La séance a changé. Actualisez le parcours.');
  const spec=(await store.get('lesson_versions',lesson.versionId)).spec,task=spec.activities.find(a=>a.id===taskId&&['CodeEditor','TestRunner'].includes(a.type));requireValue(task,'Exercice de code inconnu.');
  const result=await testActivityCode(task,code);
  await saveLearningEvent(store,req.user,{lessonId,lessonVersionId,eventId:uid('test'),type:'code_tested',activityId:taskId,payload:{code,result}});
  res.json(result);
 });
 app.post('/api/events',student,async(req,res)=>res.json(await saveLearningEvent(store,req.user,req.body)));
 app.get('/api/game/worlds',loggedIn,async(req,res)=>res.json(await Promise.all(Object.entries(catalog).map(async([id,w])=>({id,title:w.title,...await worldAccess(store,req.user,id)})))));
 app.get('/api/game/missions',teacher,async(req,res)=>res.json(await store.list('game_missions',req.user.classId)));
 app.post('/api/game/missions/:id/adapt',teacher,async(req,res)=>res.json(await adaptMission(store,req.params.id,req.user,req.body)));
 app.post('/api/game/missions/:id/validate',teacher,async(req,res)=>res.json(await validateMission(store,req.params.id,req.user,req.body)));
 app.post('/api/lessons/:id/mission',teacher,async(req,res)=>{const lesson=await assignMission(store,req.params.id,req.user,req.body);await compileCorpus(store,lesson.id,req.user);res.json(lesson);});
 app.get('/api/game/missions/:id',loggedIn,async(req,res)=>res.json(await scoped(store,'game_missions',req.params.id,req.user)));
 app.post('/api/game/runs',student,async(req,res)=>res.json(await startGame(store,req.body,req.user)));
 app.get('/api/game/runs/:id/context',student,async(req,res)=>{const run=await authorizeRun(store,req.params.id,req.user);const mission=await store.get('game_missions',run.missionId),progress=await store.get('player_progression',`${req.user.id}:${run.world}`);const worlds=structuredClone(catalog);for(const [id,w] of Object.entries(worlds))w.missions=id===mission.world?[{...mission,id:mission.localId}]:[];res.json({type:'eden:init',worlds,worldId:run.world,missionId:mission.localId,user:safeUser(req.user),resources:{blocks:[],units:library.filter(r=>mission.competencies.includes(r.code))},progress:progress?.classId===req.user.classId&&progress?.learnerId===req.user.id?progress.progress:null});});
 app.post('/api/game/runs/:id/events',student,async(req,res)=>res.json(await recordGameEvent(store,req.params.id,req.body,req.user)));
 app.post('/api/game/runs/:id/complete',student,async(req,res)=>res.json(await recordGameEvent(store,req.params.id,{...req.body,type:'mission_completed'},req.user)));
 app.post('/api/game/runs/:id/progress',student,async(req,res)=>{await store.transaction(async tx=>{const run=await authorizeRun(tx,req.params.id,req.user);const progress=req.body.progress;requireValue(progress&&typeof progress==='object'&&!Array.isArray(progress)&&JSON.stringify(progress).length<150000,'Progression invalide.');delete progress.evidence;const row={id:`${req.user.id}:${run.world}`,classId:req.user.classId,learnerId:req.user.id,world:run.world,progress};if(await tx.get('player_progression',row.id))await tx.put('player_progression',row);else await tx.insert('player_progression',row);});res.json({receivedAt:now()});});
 app.post('/api/teacher/game-evidence/:id/approve',teacher,async(req,res)=>{requireValue(req.body.reason?.trim(),'Justification requise.');const result=await store.transaction(async tx=>{const proof=await scoped(tx,'game_evidence',req.params.id,req.user);if(proof.approved)fail(409,'Preuve de jeu déjà validée.');const mission=await scoped(tx,'game_missions',proof.missionId,req.user);requireValue(Array.isArray(req.body.criteria)&&req.body.criteria.length===mission.competencies.length,'Évaluez tous les critères de mission.');for(const criterion of mission.competencies){const item=req.body.criteria.find(c=>c.criterion===criterion);requireValue(item&&['NA','EC','A1','A2'].includes(item.level),'Niveau invalide.');await tx.insert('evidence',{id:uid('evidence'),classId:req.user.classId,learnerId:proof.learnerId,criterion,sourceId:proof.id,revision:1,date:proof.createdAt.slice(0,10),level:item.level,approved:true,autonomous:req.body.autonomous===true,transfer:req.body.transfer===true,missionRunId:proof.missionRunId});}proof.approved=true;proof.status='approved';proof.approvedBy=req.user.id;proof.reason=req.body.reason;proof.criteria=req.body.criteria;await tx.put('game_evidence',proof);await tx.audit(req.user,'game.evidence_approved',proof.id,{reason:req.body.reason});return proof;});res.json(result);});
 app.get('/api/teacher/game-evidence/:id',teacher,async(req,res)=>{const proof=await scoped(store,'game_evidence',req.params.id,req.user);res.json({...proof,mission:await scoped(store,'game_missions',proof.missionId,req.user)});});
 app.post('/api/teacher/learners/:id/game-override',teacher,async(req,res)=>{await scoped(store,'learners',req.params.id,req.user);requireValue(catalog[req.body.worldId]&&req.body.reason?.trim(),'Monde et justification requis.');const row=await store.insert('game_teacher_overrides',{id:uid('override'),classId:req.user.classId,learnerId:req.params.id,worldId:req.body.worldId,enabled:req.body.enabled===true,reason:req.body.reason,authorId:req.user.id});await store.audit(req.user,'game.override',row.id,{reason:req.body.reason,enabled:row.enabled});res.json(row);});
 app.post('/api/teacher/learners/:id/access',teacher,async(req,res)=>{const result=await store.transaction(async tx=>{const learner=await scoped(tx,'learners',req.params.id,req.user),password=randomBytes(9).toString('base64url');await replacePassword(tx,learner,'student',password);await tx.audit(req.user,'learner.access_reset',learner.id);return {username:learner.username,password};});res.json(result);});
 app.patch('/api/teacher/learners/:id',teacher,async(req,res)=>{const result=await store.transaction(async tx=>{const learner=await scoped(tx,'learners',req.params.id,req.user);if(req.body.driveFolderId!==undefined)learner.driveFolderId=String(req.body.driveFolderId);await tx.put('learners',learner);return safeUser(learner);});res.json(result);});
 app.post('/api/integrations/drive/jobs',teacher,async(req,res)=>res.status(202).json(await enqueueDrive(store,req.user,req.body)));
 app.get('/api/integrations/drive/jobs',teacher,async(req,res)=>res.json(await store.list('publication_jobs',req.user.classId)));
 app.get('/api/integrations/drive/jobs/:id',teacher,async(req,res)=>res.json(await scoped(store,'publication_jobs',req.params.id,req.user)));
 app.post('/api/integrations/drive/jobs/:id/retry',teacher,async(req,res)=>res.json(await retryPublicationJob(store,req.params.id,req.user,req.body)));
 app.get('/api/integrations/drive/status',teacher,(req,res)=>res.json({configured:driveConfigured()}));
 app.get('/api/integrations/drive/students',teacher,async(req,res)=>{if(!driveConfigured())fail(503,'Drive non configuré.');res.json(await listStudents(getDrive()));});
 app.get('/api/integrations/drive/tree',teacher,async(req,res)=>{if(!driveConfigured())fail(503,'Drive non configuré.');res.json(await listChildFolders(getDrive(),String(req.query.folderId||process.env.GOOGLE_DRIVE_ELEVES_FOLDER_ID)));});
 app.post('/api/corpus/:id/publish-drive',teacher,async(req,res)=>res.json(await publishDrive(store,req.params.id,req.body,req.user)));
 app.post('/api/integrations/drive/publications',teacher,async(req,res)=>res.json(await publishDrive(store,req.body.lessonId,req.body,req.user)));
 app.get('/api/integrations/drive/publications/:id',teacher,async(req,res)=>res.json(await scoped(store,'drive_publications',req.params.id,req.user)));
 app.post('/api/integrations/drive/publications/:id/retry',teacher,async(req,res)=>{const report=await scoped(store,'drive_publications',req.params.id,req.user);res.json(await publishDrive(store,report.lessonId,{...report.spec,confirmed:req.body.confirmed},req.user,{retryId:report.id}));});
 app.get('/api/audit',teacher,async(req,res)=>res.json(await store.list('audit_log',req.user.classId)));
 app.use('/api',(_req,_res)=>fail(404,'Route API inconnue.'));
 app.get('/runtime/safe-js.mjs',(_req,res)=>res.sendFile(resolve('server/safe-js.mjs')));
 app.get('/legacy/eden-october/docs/vendor/acorn.mjs',(_req,res)=>res.sendFile(resolve('legacy/eden-october/docs/vendor/acorn.mjs')));
 app.use('/game',express.static(resolve('public/game')));
 app.use('/assets',express.static(resolve('legacy/eden-october/docs/assets')));
 app.use(express.static(resolve('public'),{index:false}));
 for(const path of ['/','/today','/teacher','/play/:world/:mission'])app.get(path,(_req,res)=>res.sendFile(resolve('public/index.html')));
 app.use((err,req,res,_next)=>{const status=err.status||500;if(status===500)console.error(err);res.status(status).json({error:status===500?'Erreur interne. Consultez le journal serveur.':err.message,...(err.details?{details:err.details}:{})});});
 return app;
}
