import {activity} from './lesson-content.mjs';
import {block,orderAndTime} from './lesson-structure.mjs';

// Authored teaching fixture: no learner, account or production data.
export function demoLesson(){
 const skills=['BC05-C1-1','BC05-C1-2'];
 const tasks=[
  activity('demo-diag','Lis la règle avant le code.','La salle demande une carte ET une réservation. Léa a une carte, mais pas de réservation. Peut-elle entrer ? Explique ton choix.',[],{expectedEvidence:'Une décision et une phrase pour l’expliquer.',duration:5}),
  activity('demo-diag-2','Retrouve une fonction.','À quoi sert return dans une fonction ? Donne un exemple, même très court.',[],{duration:5,expectedEvidence:'Une explication avec tes mots.'})
 ];
 const activities=[
  activity('guided-code','Répare la porte du club.','La porte s’ouvre trop facilement. Remplace l’opérateur pour exiger une carte ET une réservation. Teste les quatre combinaisons.',skills,{type:'CodeEditor',starter:'function peutEntrer(aCarte, aReserve) {\n  return aCarte || aReserve;\n}',correctionMode:'javascript',tests:[{invoke:'peutEntrer',argsJSON:'[true,false]',expectedJSON:'false'},{invoke:'peutEntrer',argsJSON:'[false,true]',expectedJSON:'false'},{invoke:'peutEntrer',argsJSON:'[true,true]',expectedJSON:'true'},{invoke:'peutEntrer',argsJSON:'[false,false]',expectedJSON:'false'}],reference:'Remplacer || par &&. Les deux conditions doivent être vraies.',expectedEvidence:'La fonction corrigée et les quatre cas vérifiés.'}),
  activity('guided-quiz','Un dernier cas à vérifier.','Léa a une réservation, mais sa carte est absente. Que doit renvoyer la fonction ?',skills,{type:'Quiz',options:['true : la réservation suffit.','false : les deux conditions sont nécessaires.','Le résultat dépend de l’ordre des paramètres.'],correctionMode:'exact',expectedAnswer:'false : les deux conditions sont nécessaires.',reference:'Le ET exige deux conditions vraies.',duration:2,expectedEvidence:'Le choix qui correspond à la règle ET.'}),
  activity('guided-blank','La règle avec tes mots.','Complète les deux repères. Utilise « deux » ou « au moins une ».',skills,{type:'FillBlank',options:['Avec ET, il faut … conditions vraies.','Avec OU, il faut … condition vraie.'],correctionMode:'structured',expectedAnswer:'{"0":"deux","1":"au moins une"}',reference:'ET : deux. OU : au moins une.',expectedEvidence:'Deux repères que tu sais expliquer.',duration:2}),
  activity('transfer','Ajoute un arrêt d’urgence.','Une alarme doit bloquer l’accès, même avec une carte et une réservation. Écris peutEntrer(aCarte, aReserve, alarme). Teste un accès autorisé, une carte absente et une alarme active.',skills,{type:'CodeEditor',starter:'function peutEntrer(aCarte, aReserve, alarme) {\n  // La carte ET la réservation, mais PAS l’alarme.\n  return false;\n}',correctionMode:'javascript',tests:[{invoke:'peutEntrer',argsJSON:'[true,true,false]',expectedJSON:'true'},{invoke:'peutEntrer',argsJSON:'[false,true,false]',expectedJSON:'false'},{invoke:'peutEntrer',argsJSON:'[true,true,true]',expectedJSON:'false'}],reference:'return aCarte && aReserve && !alarme;',expectedEvidence:'Une fonction et trois cas, dont un refus causé par l’alarme.'}),
  activity('extension','Une invitation change la règle.','Une invitation permet maintenant d’entrer sans carte ni réservation. L’alarme bloque toujours tout le monde. Écris d’abord la règle avec tes mots. Donne deux cas qui pourraient piéger une mauvaise solution.',skills,{expectedEvidence:'Une nouvelle règle et deux cas de test expliqués.'}),
  activity('exit','Ton ticket de sortie','Explique la différence entre ET et OU avec un exemple du club. Écris ensuite un cas que tu avais oublié de tester. Termine par ce que tu veux encore éclaircir.',skills,{type:'Reflection',correctionMode:'none',expectedEvidence:'Un exemple, un cas oublié et ton prochain pas.'})
 ];
 const blocks=[
  block('opening','LessonHero','opening','Deux règles. Une décision.','Une carte. Une réservation. La porte du club doit-elle s’ouvrir ? Aujourd’hui, tu transformes une règle simple en code qui tient la route.',4,[],skills),
  block('diagnostic','Diagnostic','diagnostic','Évaluation','Réponds sans aide, puis rends ton travail. Tu peux rendre une réponse incomplète.',10),
  block('concept','ConceptCard','understand','ET, OU, NON. Tout part de là.','Un booléen est une valeur qui vaut vrai ou faux. Une condition utilise cette valeur pour prendre une décision.\n\nET demande deux conditions vraies. OU demande au moins une condition vraie. NON inverse une valeur : vrai devient faux, et faux devient vrai.\n\nAu club, la carte seule ne suffit pas. La réservation seule non plus. Il faut les deux. C’est une règle ET.',12,[],skills,{diagram:['Carte valide + réservation → ET → Accès autorisé','Une condition manque → Accès refusé'],takeaways:['ET : les deux conditions doivent être vraies.','OU : au moins une condition doit être vraie.'],hint:'Attention : dans le langage courant, « ou » peut sembler exclure un choix. Ici, OU accepte aussi le cas où les deux conditions sont vraies.'}),
  block('observe','LiveCode','observe','Lis. Prévois. Puis vérifie.','const aCarte = true;\nconst aReserve = false;\n\nconst acces = aCarte && aReserve;\nconsole.log(acces); // false',8,[],skills,{steps:['La carte est valide : aCarte vaut true.','La réservation manque : aReserve vaut false.','Le ET exige les deux. acces vaut donc false.'],check:'Si la réservation devient vraie, que va afficher la console ?',takeaways:['&& traduit ET en JavaScript. Un seul false suffit à refuser l’accès.']}),
  block('guided','Activity','guided','On répare ensemble.','Tu as lu un exemple. Maintenant, utilise la règle pour corriger une porte trop accueillante.',18,['guided-code','guided-quiz','guided-blank'],skills,{steps:['Lis la règle attendue : carte ET réservation.','Repère l’opérateur qui ne correspond pas à cette règle.','Change-le, puis teste aussi les cas qui doivent être refusés.'],hint:'|| signifie OU. Pour exiger deux conditions vraies, utilise l’opérateur ET : &&.',check:'Seul le cas true / true doit ouvrir la porte.'}),
  block('autonomy','Activity','autonomy','À toi de garder la porte.','Ajoute une nouvelle contrainte sans regarder le modèle. Commence par prévoir les cas.',20,['transfer'],skills,{check:'L’alarme active refuse toujours l’accès. Sans alarme, la carte et la réservation restent nécessaires.'}),
  block('extension','Activity','extend','Et si tu changeais les règles ?','Le club accueille des invités. Réinvestis ET, OU et NON dans une règle un peu plus riche.',10,['extension'],skills,{check:'Ton invitation peut remplacer la carte et la réservation. Elle ne peut jamais désactiver l’alarme.'}),
  block('exit','Reflection','summary','Tu peux maintenant expliquer la règle.','Reviens à la porte du club. Quelle méthode te permet de décider sans deviner ?',8,['exit'],skills,{takeaways:['ET exige deux conditions vraies. OU en exige au moins une.','NON inverse un booléen. !alarme signifie : l’alarme est inactive.','Teste les autorisations ET les refus. Une porte qui s’ouvre une fois n’est pas encore une porte fiable.']})
 ];
 orderAndTime({blocks,activities},90,10);
 return {schemaVersion:'1.0',lessonId:'DEMO-LOGIC',lessonVersion:1,classId:'DEMO',date:'2026-10-04',planEntryId:'demo',planVersion:1,sequence:'01 · La logique en action',title:'Deux règles. Une décision.',skills,objectives:['Traduire une règle avec ET, OU et NON.','Prévoir un résultat avant de lancer le code.','Vérifier les cas qui passent… et ceux qui bloquent.'],prerequisites:[],reactivation:[],diagnostic:{id:'DEMO-LOGIC:diagnostic',kind:'baseline',sourceLessonRunId:null,sourceLessonVersion:null,duration:10,criteria:[],tasks,rubric:tasks.map((t,i)=>({id:`item-${i}`,criterion:'baseline',taskId:t.id,label:t.expectedEvidence,max:10,a1:5,a2:7.5}))},timeline:blocks.map(b=>({blockId:b.id,minutes:b.minutes})),blocks,activities,slides:[],resources:skills,codeStation:null,teacherGuide:'Faire prévoir les résultats avant de tester. Distinguer ET et OU avec le cas true/true. Faire verbaliser le rôle de !alarme. Démonstration de 90 minutes, sans accès aux données élèves.',studentFlow:blocks.map(b=>b.id),sourceVersions:{curriculumVersion:'demo',planVersion:1,previousLessonRunId:null}};
}
