/* World Arcade — vanilla front end. No credentials are persisted or transmitted.
   Integrate real auth / ranking through the host adapter, not through this demo state. */
'use strict';
(() => {
 const D=window.ArcadeData;
 const $=(s,root=document)=>root.querySelector(s);
 const $$=(s,root=document)=>[...root.querySelectorAll(s)];
 const icon=(id,cls='')=>`<svg class="icon ${cls}" aria-hidden="true"><use href="#i-${id}"/></svg>`;
 const esc=(value)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const nf=new Intl.NumberFormat('fr-FR');
 const storageKey='eden.world-arcade.front.v1';
 const validRoutes=['arcade','joueurs','classement','profil','badges','reglages'];
 const labels={arcade:'WORLD ARCADE',joueurs:'LES JOUEURS',classement:'CLASSEMENT',profil:'MON PROFIL',badges:'LES GRADES',reglages:'RÉGLAGES'};
 const defaultPrefs={sound:false,reducedMotion:window.matchMedia('(prefers-reduced-motion: reduce)').matches,crt:true};
 let saved={};try{saved=JSON.parse(localStorage.getItem(storageKey)||'{}')||{};}catch{saved={};}
 const validProfile=saved.profile && typeof saved.profile.name==='string' && saved.profile.name.length<=20;
 const state={
  route:'arcade',period:'week',scope:'all',world:'all',search:'',sort:'name',rosterScope:'all',
  profile:validProfile?{name:saved.profile.name,avatar:Math.max(1,Math.min(15,Number(saved.profile.avatar)||1))}:null,
  prefs:{...defaultPrefs,...Object.fromEntries(Object.entries(saved.prefs||{}).filter(([k,v])=>k in defaultPrefs&&typeof v==='boolean'))},
  completed:{'code-station':Boolean(saved.completed?.['code-station']),'cyber-funk':Boolean(saved.completed?.['cyber-funk'])},
  authTab:'login',chosenAvatar:1,activeGame:null
 };
 let modalReturnFocus=null;
 function save(){
  try{localStorage.setItem(storageKey,JSON.stringify({version:1,profile:state.profile,prefs:state.prefs,completed:state.completed}));return true;}
  catch{toast('Ton navigateur ne permet pas la sauvegarde locale. La session reste jouable.');return false;}
 }
 function toast(message){const el=document.createElement('div');el.className='toast';el.innerHTML=icon('check')+esc(message);$('#toasts').appendChild(el);while($('#toasts').children.length>3)$('#toasts').firstElementChild.remove();setTimeout(()=>el.remove(),5200);}
 const Audio={ctx:null,timer:null,step:0,
  beep(frequency=480,duration=.07,volume=.025){
   if(!state.prefs.sound || document.hidden)return;
   try{this.ctx??=new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});
    const osc=this.ctx.createOscillator(),gain=this.ctx.createGain(),now=this.ctx.currentTime;osc.type='triangle';osc.frequency.value=frequency;gain.gain.setValueAtTime(volume,now);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(gain);gain.connect(this.ctx.destination);osc.start(now);osc.stop(now+duration);osc.onended=()=>{osc.disconnect();gain.disconnect();};
   }catch{/* Sound is optional; browsers may deny AudioContext. */}
  },
  sync(){clearInterval(this.timer);this.timer=null;if(!state.prefs.sound||document.hidden)return;
   this.beep(392,.15,.014);const notes=[196,0,293.66,0,261.63,0,392,0,196,0,329.63,0,293.66,0,261.63,0];
   this.timer=setInterval(()=>{const f=notes[this.step++%notes.length];if(f)this.beep(f,.25,.012);},310);
  }
 };
 function applyPreferences(){document.body.classList.toggle('reduce-motion',state.prefs.reducedMotion);document.body.classList.toggle('no-crt',!state.prefs.crt);$$('.sound-toggle').forEach(b=>{b.innerHTML=icon(state.prefs.sound?'sound':'mute');b.setAttribute('aria-label',state.prefs.sound?'Couper le son':'Activer le son');b.setAttribute('aria-pressed',String(state.prefs.sound));});}
 function rankFor(p){return D.ranks.find(r=>r.id===p.rank)||D.ranks[0];}
 function badge(rank,cls=''){
  const level=rank.symbol||1;let inside='';
  if(level<4){for(let i=0;i<level;i++)inside+=`<path d="m8 ${10+i*4} 4 3 4-3"/>`;}
  else if(level<7)inside='<path d="m12 7 2 4 4 .5-3 3 .7 4.5-3.7-2.1-3.7 2.1.7-4.5-3-3 4-.5Z"/>';
  else inside='<path d="m7 11 3 2 2-6 2 6 3-2-2 8H9Z"/><path d="M8 21h8"/>';
  return `<svg class="rank-badge ${cls}" viewBox="0 0 24 29" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linejoin="round" aria-hidden="true"><path d="m12 1 9 4v13l-9 10-9-10V5Z"/><path opacity=".5" d="m12 4 6 3v10l-6 7-6-7V7Z"/>${inside}${level>5?'<path d="M1 6v12l4 5M23 6v12l-4 5"/>':''}</svg>`;
 }
 function rankLabel(p){const r=rankFor(p);return `<span class="rank-label" style="color:${r.color}">${badge(r)}<span>${esc(r.name)} ${esc(p.division||'I')}</span></span>`;}
 function avatar(p,cls='avatar'){return `<img class="${cls}" src="${D.avatar(p.avatar)}" alt="" width="82" height="92" loading="lazy">`;}
 function profilePlayer(){return {id:'local',name:state.profile?.name||'Visiteur',avatar:state.profile?.avatar||1,rank:'rookie',division:'I',scores:{week:points(),month:points(),all:points()},missions:Object.values(state.completed).filter(Boolean).length};}
 function points(){return Object.values(state.completed).filter(Boolean).length*200;}
 function ranking(){return D.players.filter(p=>state.scope==='all'||p.scope===state.scope).map(p=>({...p,score:Math.round(p.scores[state.period]*(state.world==='all'?1:p.world === state.world ? .65 : .35))})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'fr')).slice(0,5);}
 function periods(){return `<div class="segmented" aria-label="Période du classement">${[['week','Semaine'],['month','Mois'],['all','Toujours']].map(([v,t])=>`<button data-action="period" data-value="${v}" aria-pressed="${state.period===v}">${t}</button>`).join('')}</div>`;}
 function leaderboardRow(p,i){return `<li><button class="leaderboard-row" data-action="player" data-id="${p.id}" aria-label="${esc(p.name)}, place ${i+1}, ${nf.format(p.score)} XP"><span class="position p${i+1}">${i+1}</span>${avatar(p)}<span><span class="player-name">${esc(p.name)}</span>${rankLabel(p)}</span><span class="score">${nf.format(p.score)}<span>XP</span></span></button></li>`;}
 function leaderboardPanel(){return `<section class="panel leaderboard-panel" aria-labelledby="top5-title"><div class="section-head"><h2 id="top5-title">TOP 5</h2><span class="section-signal"><i></i> COMMUNAUTÉ</span></div>${periods()}<ol class="leaderboard-list">${ranking().map(leaderboardRow).join('')}</ol><div class="leaderboard-foot"><span>${state.profile?'Ta place : non classé':'Et si la prochaine place était la tienne ?'}</span><a href="#classement" class="text-button" aria-label="Voir le classement">${icon('arrow')}</a></div></section>`;}
 function avatarTile(p){return `<button class="avatar-tile" data-action="player" data-id="${p.id}" aria-label="Voir le profil de ${esc(p.name)}">${avatar(p)}${p.online?'<i class="online-dot" aria-hidden="true"></i>':''}<span>${esc(p.name)}</span></button>`;}
 function playersPanel(){return `<section class="panel players-panel" aria-labelledby="players-title"><div class="section-head"><h2 id="players-title">LES JOUEURS <span class="count">${D.players.length}</span></h2><a class="text-button" href="#joueurs">Voir tous ${icon('arrow')}</a></div><div class="avatar-grid">${D.players.slice(0,14).map(avatarTile).join('')}<a class="avatar-tile more" href="#joueurs" aria-label="Voir les ${D.players.length} joueurs"><strong>+${D.players.length-14}</strong><span>joueurs</span></a></div></section>`;}
 function cabinet(g){return `<article class="cabinet ${g.className}" aria-labelledby="title-${g.id}"><div class="cabinet-housing"><div class="cabinet-marquee">${g.id==='code-station'?'<span class="marquee-chevron" aria-hidden="true">‹</span>':''}<span class="marquee-name">${g.title}</span>${g.id==='code-station'?'<span class="marquee-chevron" aria-hidden="true">›</span>':''}</div><div class="speaker-strip" aria-hidden="true"></div><div class="screen-frame"><img class="game-art" src="${g.image}" alt="${g.id==='code-station'?'Un équipage pixel art dans la station spatiale':'La skyline néon de Neo Eden en 3026'}" width="391" height="207"><button class="game-information" data-action="game-info" data-id="${g.id}" aria-label="À propos de ${g.short}">${icon('info')}</button><div class="screen-info"><p class="eyebrow">${g.number} / ${g.eyebrow}</p><h2 class="screen-game-title" id="title-${g.id}">${g.title}</h2></div></div><div class="cabinet-console"><div class="console-decoration" aria-hidden="true"><span class="mini-buttons"><i></i><i></i><i></i></span></div><button class="arcade-play" data-action="play" data-id="${g.id}" aria-label="${state.completed[g.id]?'Rejouer à':'Jouer à'} ${g.short}">${state.completed[g.id]?'REJOUER':'JOUER'} ${icon('chevron')}</button></div><div class="cabinet-base"><p class="cabinet-description">${g.description}</p><div class="cabinet-keys">${state.completed[g.id]?'✓ MISSION TERMINÉE':g.keys}</div><div class="coin-slot" aria-hidden="true"></div></div></div><div class="cabinet-foot" aria-hidden="true"></div><div class="cabinet-reflection" aria-hidden="true"></div></article>`;}
 function renderArcade(){return `<div class="arcade-grid"><div class="arcade-main"><div class="city-banner" role="img" aria-label="Neo Eden, ville futuriste éclairée de néons"><span class="banner-caption">NEXT STOP.<br>ANOTHER WORLD.</span><span class="banner-tag"><i></i> NEO EDEN / 3026</span></div><div class="arcade-heading"><div><h1 class="display">CHOISIS TON MONDE</h1><p>Deux univers. À toi de jouer.</p></div><div class="heading-mark" aria-hidden="true"><i></i><i></i><i></i></div></div><div class="cabinets">${D.games.map(cabinet).join('')}</div><div class="arcade-bottomline"><span class="world-indicator"><span class="status-dot"></span> 2 mondes à explorer</span><button class="text-button" data-action="shortcuts">Les commandes ${icon('arrow')}</button></div></div><aside class="side-panels">${leaderboardPanel()}${playersPanel()}<div class="side-promo">${icon('badge')}<div><strong>Un premier pas. Un nouveau grade.</strong><p>Découvre la voie des Explorers.</p></div><a href="#badges" class="icon-button" aria-label="Découvrir les grades">${icon('chevron')}</a></div></aside></div>`;}
 function pageHero(overline,title,description,counter=''){return `<header class="page-hero"><p class="eyebrow">${overline}</p><div class="page-hero-row"><div><h1 class="display">${title}</h1><p>${description}</p></div>${counter?`<div class="page-counter" aria-hidden="true">${counter}</div>`:''}</div></header>`;}
 function playerCard(p){return `<button class="player-card" data-action="player" data-id="${p.id}" aria-label="Voir ${esc(p.name)}, ${rankFor(p).name} ${p.division}">${avatar(p,'roster-avatar')}${p.online?'<i class="card-status" aria-hidden="true"></i>':''}<h2>${esc(p.name)}</h2>${rankLabel(p)}<span class="player-card-footer"><span>${p.missions} missions</span>${icon('arrow')}</span></button>`;}
 function roster(){const q=state.search.toLocaleLowerCase('fr');const players=D.players.filter(p=>p.name.toLocaleLowerCase('fr').includes(q)&&(state.rosterScope==='all'||p.scope===state.rosterScope));players.sort(state.sort==='xp'?(a,b)=>b.scores.all-a.scores.all:state.sort==='rank'?(a,b)=>rankFor(b).symbol-rankFor(a).symbol||b.division.length-a.division.length||a.name.localeCompare(b.name):(a,b)=>a.name.localeCompare(b.name,'fr'));return players.length?players.map(playerCard).join(''):`<div class="empty-state">${icon('search')}<h2>Aucun joueur trouvé</h2><p>Essaie un autre pseudo.</p></div>`;}
 function renderPlayers(){return pageHero('LE ROSTER','LES JOUEURS','Un pseudo, un avatar, un univers à explorer.',String(D.players.length).padStart(2,'0'))+`<div class="toolbar"><label class="search-field">${icon('search')}<span class="sr-only">Rechercher un pseudo</span><input id="player-search" type="search" autocomplete="off" placeholder="Rechercher un pseudo…" value="${esc(state.search)}"></label><div class="filter-set"><label class="sr-only" for="roster-scope">Groupe de joueurs</label><select class="select-field" id="roster-scope"><option value="all" ${state.rosterScope==='all'?'selected':''}>Tous les joueurs</option><option value="class" ${state.rosterScope==='class'?'selected':''}>Classe démo</option><option value="community" ${state.rosterScope==='community'?'selected':''}>Communauté démo</option></select><label class="sr-only" for="roster-sort">Trier les joueurs</label><select class="select-field" id="roster-sort"><option value="name" ${state.sort==='name'?'selected':''}>Par pseudo</option><option value="rank" ${state.sort==='rank'?'selected':''}>Par grade</option><option value="xp" ${state.sort==='xp'?'selected':''}>Par XP</option></select></div></div><div class="players-roster" id="players-roster">${roster()}</div>`;}
 function renderRanking(){const rows=ranking();return pageHero('LE TABLEAU DES SCORES','LE TOP 5','Les cinq premières places. Ton prochain défi ne dépend que de toi.','05')+`<div class="leaderboard-page-tools">${periods()}<div class="filter-set"><label class="sr-only" for="ranking-scope">Groupe du classement</label><select class="select-field" id="ranking-scope"><option value="all" ${state.scope==='all'?'selected':''}>Tous les joueurs</option><option value="class" ${state.scope==='class'?'selected':''}>Classe démo</option><option value="community" ${state.scope==='community'?'selected':''}>Communauté démo</option></select><label class="sr-only" for="ranking-world">Jeu du classement</label><select class="select-field" id="ranking-world"><option value="all" ${state.world==='all'?'selected':''}>Tous les mondes</option>${D.games.map(g=>`<option value="${g.id}" ${state.world===g.id?'selected':''}>${g.short}</option>`).join('')}</select></div></div><div class="podium">${rows.slice(0,3).map((p,i)=>`<button class="podium-card" data-action="player" data-id="${p.id}" aria-label="Place ${i+1}, ${esc(p.name)}"><span class="podium-number">0${i+1}</span>${avatar(p)}<h2>${esc(p.name)}</h2>${rankLabel(p)}<p class="podium-score">${nf.format(p.score)} <span>XP</span></p></button>`).join('')}</div><div class="expanded-ranking"><ol class="leaderboard-list">${rows.slice(3,5).map((p,i)=>leaderboardRow(p,i+3)).join('')}</ol></div><p class="ranking-note">${icon('info')}Ces scores et joueurs sont fictifs. Tes missions de démonstration restent dans ce navigateur ; elles ne sont pas publiées au classement.</p>`;}
 function renderRanks(){const current=state.profile?'rookie':null;return pageHero('TA PROGRESSION','CHAQUE GRADE COMPTE','De Rookie à Prestige, trois divisions par grade. La place au classement et le grade sont deux choses différentes.')+`<div class="ranks-grid">${D.ranks.map((r,i)=>`<article class="rank-card ${r.id===current?'current':''}" style="--rank-color:${r.color}"><span class="rank-card-index">${String(i+1).padStart(2,'0')}</span>${badge(r)}<h2>${r.name}${r.id===current?'<span class="rank-current">TON GRADE</span>':''}</h2><p>${r.description}</p><div class="rank-divisions"><span>I</span><span>II</span><span>III</span></div></article>`).join('')}</div><p class="ranking-note">${icon('info')}Cette démo présente les grades. Aucun seuil d’XP ni passage de grade automatique n’est défini. Les promotions seront liées aux épreuves du jeu connecté.</p>`;}
 function renderProfile(){if(!state.profile)return pageHero('TON ESPACE','PRENDS TA PLACE','Choisis ton avatar et retrouve tes missions dans ce navigateur.')+`<section class="empty-state">${icon('user')}<h2>Ton aventure, ton profil.</h2><p>Entre avec un profil de démonstration pour personnaliser ton pseudo et ton avatar.</p><button class="button primary" data-action="auth" data-tab="register">Créer un profil ${icon('arrow')}</button></section>`;
  const p=profilePlayer();return pageHero('TON ESPACE','PLAYER ONE','Ton profil et tes missions de démonstration.')+`<section class="profile-hero">${avatar(p)}<div><p class="eyebrow">JOUEUR</p><h2>${esc(p.name)}</h2>${rankLabel(p)}</div><div class="profile-controls"><button class="button" data-action="edit-profile">Modifier le profil</button><button class="button ghost" data-action="logout">${icon('log-out')} Se déconnecter</button></div></section><div class="profile-stats"><div class="stat-card"><span>XP de démo</span><strong>${points()}</strong></div><div class="stat-card"><span>Missions réussies</span><strong>${p.missions} / 2</strong></div><div class="stat-card"><span>Grade actuel</span><strong>ROOKIE I</strong></div></div><div class="section-head"><h2>Tes mondes</h2></div><div class="profile-missions">${D.games.map(g=>`<article class="mission-summary"><img src="${g.image}" alt="" width="90" height="65"><div><h3>${g.short}</h3><p>${state.completed[g.id]?'Mission de démo terminée':'Une mission à découvrir'}</p></div><button class="button small" data-action="play" data-id="${g.id}">${state.completed[g.id]?'Rejouer':'Jouer'}</button></article>`).join('')}</div>`;
 }
 function switchRow(id,title,description){return `<div class="setting-row"><div class="setting-copy"><strong id="label-${id}">${title}</strong><p id="help-${id}">${description}</p></div><button class="switch" role="switch" aria-checked="${state.prefs[id]}" aria-labelledby="label-${id}" aria-describedby="help-${id}" data-action="preference" data-id="${id}"></button></div>`;}
 function renderSettings(){return pageHero('À TA FAÇON','LES RÉGLAGES','Juste ce qu’il faut pour te sentir dans ton élément.')+`<div class="settings-grid"><section class="panel settings-panel"><h2>L’ambiance</h2>${switchRow('sound','Son de l’arcade','Une boucle chiptune discrète et de courts sons d’interface. Désactivés au départ.')}${switchRow('reducedMotion','Réduire les animations','Supprime les transitions et mouvements décoratifs. Le jeu conserve ses déplacements.')}${switchRow('crt','Effet écran rétro','Ajoute une légère trame aux écrans des bornes, sans modifier les textes.')}</section><section class="panel settings-panel settings-info"><h2>Dans ce navigateur</h2><p>Le pseudo, l’avatar, les préférences et les deux missions terminées sont enregistrés localement. Aucun e-mail ni mot de passe n’est conservé.</p><p>La réinitialisation efface uniquement les données de cette démonstration sur cet appareil.</p><button class="button danger" data-action="confirm-reset">${icon('reload')} Réinitialiser la démo</button></section></div>`;}
 function updateAccount(){const p=profilePlayer();$('#account-slot').innerHTML=`<button class="account-button" ${state.profile?'data-action="profile"':'data-action="auth"'}>${state.profile?avatar(p,'account-avatar'):`<span class="account-avatar guest-avatar">${icon('user')}</span>`}<span><span class="account-name">${state.profile?esc(p.name):'Connexion'}</span><span class="account-rank" style="display:block">${state.profile?'Rookie I':'Joueur invité'}</span></span>${icon('chevron')}</button>`;}
 function render(){const routes={arcade:renderArcade,joueurs:renderPlayers,classement:renderRanking,profil:renderProfile,badges:renderRanks,reglages:renderSettings};$('#main-content').innerHTML=(routes[state.route]||renderArcade)();$('#route-label').textContent=labels[state.route];$$('[data-route]').forEach(a=>{const active=a.dataset.route===state.route;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});updateAccount();document.title=`${labels[state.route]} — EDEN`;applyPreferences();}
 function enter(route='arcade',focus=false){$('#splash').hidden=true;$('#app').hidden=false;state.route=validRoutes.includes(route)?route:'arcade';if(state.route==='arcade'){state.scope='all';state.world='all';}render();if(focus)$('#main-content').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
 function showHome(){if($('#game-modal').open)closeGame();if($('#modal').open)$('#modal').close();history.replaceState(null,'',location.href.split('#')[0]);$('#splash').hidden=false;$('#app').hidden=true;document.title='World Arcade — EDEN';$('#start-button').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
 function go(route){if(location.hash===`#${route}`)enter(route,true);else location.hash=route;}
 function modalHeader(title,eyebrow='WORLD ARCADE'){return `<div class="modal-heading"><div><p class="eyebrow">${eyebrow}</p><h2 id="modal-title">${title}</h2></div><button class="icon-button" data-action="close-modal" aria-label="Fermer">${icon('close')}</button></div>`;}
 function openModal(html){modalReturnFocus=document.activeElement;$('#modal-body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
 function closeModal(){if($('#modal').open)$('#modal').close();}
 function showAbout(){openModal(modalHeader('L’arcade, en démo')+`<p class="modal-copy">Ce front est une démonstration autonome : les deux mini-jeux fonctionnent, les menus sont interactifs et la progression est conservée sur cet appareil.</p><p class="modal-copy">Les joueurs, scores, groupes et présences sont fictifs. Les formulaires simulent l’entrée dans un profil local ; aucun compte en ligne n’est créé.</p><button class="button primary full" data-action="close-modal">C’est parti ${icon('arrow')}</button>`);}
 function showShortcuts(){openModal(modalHeader('Les commandes')+`<div class="shortcut-list"><span>Entrer dans l’arcade</span><kbd>Entrée</kbd><span>Fermer une fenêtre</span><kbd>Échap</kbd><span>Naviguer dans l’interface</span><kbd>Tab</kbd><span>Se déplacer dans Code Station</span><span><kbd>↑</kbd> <kbd>←</kbd> <kbd>↓</kbd> <kbd>→</kbd></span><span>Inspecter un terminal</span><kbd>E</kbd><span>Se déplacer dans Cyber Funk</span><span><kbd>←</kbd> <kbd>→</kbd></span><span>Sauter dans Cyber Funk</span><kbd>Espace</kbd><span>Mettre une partie en pause</span><kbd>P</kbd><span>Recommencer une partie</span><kbd>R</kbd></div><p class="form-note">ZQSD et WASD fonctionnent aussi. Les commandes tactiles sont disponibles sur les petits écrans.</p>`);}
 function showPlayer(id){const p=D.players.find(x=>x.id===id);if(!p)return;openModal(modalHeader('Fiche joueur','LE ROSTER')+`<div class="player-detail">${avatar(p)}<h3>${esc(p.name)}</h3>${rankLabel(p)}<div class="detail-stat-grid"><div><strong>${nf.format(p.scores.all)}</strong><span>XP AU TOTAL</span></div><div><strong>${p.missions}</strong><span>MISSIONS</span></div></div><p class="form-note">Profil fictif de démonstration. Les véritables profils publics devront afficher uniquement les informations choisies par leur joueur.</p></div>`);}
 function auth(tab='login'){
  state.authTab=tab;const register=tab==='register';openModal(modalHeader(register?'REJOINS L’ARCADE':'BON RETOUR', 'TON PROFIL')+`<div class="segmented auth-tabs" aria-label="Connexion ou inscription"><button data-action="auth-tab" data-tab="login" aria-pressed="${!register}">Connexion</button><button data-action="auth-tab" data-tab="register" aria-pressed="${register}">Inscription</button></div><form id="auth-form"><div class="form-error" id="auth-error" role="alert" hidden></div>${register?'<label class="form-field"><span>Pseudo</span><input name="nickname" id="auth-nickname" placeholder="Ton nom dans l’arcade" required minlength="2" maxlength="20" autocomplete="nickname" pattern="[A-Za-z0-9À-ÿ_\\- ]{2,20}"><small>2 à 20 caractères. Pas de nom complet nécessaire.</small></label>':''}<label class="form-field"><span>Adresse e-mail</span><input name="email" type="email" id="auth-email" required autocomplete="email" placeholder="joueur@example.test" maxlength="254"></label><div class="form-field"><label for="auth-password">Mot de passe</label><div class="password-wrap"><input name="password" type="password" id="auth-password" required minlength="12" maxlength="128" autocomplete="${register?'new-password':'current-password'}" placeholder="12 caractères minimum"><button class="icon-button" data-action="password" type="button" aria-label="Afficher le mot de passe">${icon('eye')}</button></div><small>Utilise des informations fictives pour cette démonstration.</small></div>${register?'<label class="form-check"><input name="demo-consent" type="checkbox" required><span>J’ai compris qu’il s’agit d’un profil local de démonstration, sans création de compte en ligne.</span></label>':''}<button class="button primary full" type="submit">${register?'Créer mon profil':'Se connecter'} ${icon('arrow')}</button><p class="form-note">Démo uniquement : e-mail et mot de passe ne sont ni envoyés ni enregistrés. Seuls ton pseudo et ton avatar seront conservés dans ce navigateur.</p></form>`);
 }
 function showEditProfile(){if(!state.profile)return auth('register');state.chosenAvatar=state.profile.avatar;openModal(modalHeader('Ton personnage')+`<form id="profile-form"><label class="form-field"><span>Pseudo</span><input id="profile-name" value="${esc(state.profile.name)}" required minlength="2" maxlength="20" autocomplete="nickname"></label><p class="eyebrow">TON AVATAR</p><div class="avatar-options" aria-label="Choisir un avatar">${Array.from({length:15},(_,i)=>`<button type="button" class="avatar-option ${state.chosenAvatar===i+1?'selected':''}" data-action="choose-avatar" data-id="${i+1}" aria-label="Avatar ${i+1}" aria-pressed="${state.chosenAvatar===i+1}"><img src="${D.avatar(i+1)}" alt="" width="82" height="92"></button>`).join('')}</div><button class="button primary full" type="submit">Enregistrer ${icon('check')}</button></form>`);}
 function showGameInfo(id){const g=D.games.find(g=>g.id===id);if(!g)return;openModal(modalHeader(g.short,g.tag)+`<img class="modal-image" src="${g.image}" alt=""><p class="modal-copy">${g.details}</p><div class="modal-feature">${icon('game')} ${g.keys} · ${g.chapter}</div><button class="button primary full" data-action="play" data-id="${g.id}">Jouer à la démo ${icon('arrow')}</button>`);}
 function startGame(id){const g=D.games.find(g=>g.id===id);if(!g)return;closeModal();
  // Host can prevent this event and use an existing game route, iframe or engine.
  const event=new CustomEvent('worldarcade:launch',{cancelable:true,detail:{gameId:id,game:g}});
  if(!window.dispatchEvent(event))return;
  state.activeGame=id;$('#game-dialog-title').textContent=g.short;$('#game-dialog-overline').textContent='DÉMO JOUABLE / '+g.chapter;$('#game-keys').innerHTML=id==='code-station'?'<kbd>↑</kbd> <kbd>←</kbd> <kbd>↓</kbd> <kbd>→</kbd> Déplacer · <kbd>E</kbd> Interagir · <kbd>P</kbd> Pause':'<kbd>←</kbd> <kbd>→</kbd> Déplacer · <kbd>Espace</kbd> Sauter · <kbd>P</kbd> Pause';
  const action=$('.touch-action');action.textContent=id==='code-station'?'E':'SAUT';action.setAttribute('aria-label',id==='code-station'?'Inspecter le terminal':'Sauter');
  $$('.touch-controls [data-key="ArrowUp"],.touch-controls [data-key="ArrowDown"]').forEach(x=>x.hidden=id!=='code-station');
  $('#game-pause').hidden=true;$('#game-modal').showModal();
  window.ArcadeGames.start(id,{canvas:$('#game-canvas'),panel:$('#mission-panel'),onComplete:()=>completeGame(id),onPause:(paused)=>$('#game-pause').hidden=!paused,sound:(f)=>Audio.beep(f,.1,.02)});
  $('#game-canvas').focus({preventScroll:true});
 }
 function completeGame(id){const already=state.completed[id];state.completed[id]=true;save();if(!already)toast('Mission réussie ! +200 XP de démo.');if(!$('#app').hidden)render();window.dispatchEvent(new CustomEvent('worldarcade:demo-complete',{detail:{gameId:id,localOnly:true}}));}
 function closeGame(){window.ArcadeGames.stop();state.activeGame=null;if(document.fullscreenElement=== $('#game-modal'))document.exitFullscreen().catch(()=>{});$('#game-modal').close();}
 async function fullScreen(){const target=$('#game-modal');try{if(document.fullscreenElement)await document.exitFullscreen();else if(target.requestFullscreen)await target.requestFullscreen();else toast('Le plein écran n’est pas disponible dans ce navigateur.');}catch{toast('Le navigateur a refusé le plein écran.');}}
 function resetDemo(){try{localStorage.removeItem(storageKey);}catch{}state.profile=null;state.completed={'code-station':false,'cyber-funk':false};state.prefs={...defaultPrefs};Audio.sync();applyPreferences();closeModal();render();toast('La démonstration a été réinitialisée.');}
 document.addEventListener('click',e=>{
  const el=e.target.closest('[data-action],.sound-toggle');if(!el)return;
  if(el.classList.contains('sound-toggle')){state.prefs.sound=!state.prefs.sound;save();applyPreferences();Audio.sync();if(state.route==='reglages'&&!$('#app').hidden)render();return;}
  const action=el.dataset.action,id=el.dataset.id;Audio.beep(650,.035,.02);
  switch(action){
   case 'home':showHome();break;case 'profile':go('profil');break;
   case 'about':showAbout();break;case 'shortcuts':showShortcuts();break;
   case 'close-modal':closeModal();break;
   case 'player':showPlayer(id);break;
   case 'period':state.period=el.dataset.value;render();break;
   case 'auth':auth(el.dataset.tab||'login');break;
   case 'auth-tab':auth(el.dataset.tab);break;
   case 'password':{const input=$('#auth-password');const showing=input.type==='password';input.type=showing?'text':'password';el.setAttribute('aria-label',showing?'Masquer le mot de passe':'Afficher le mot de passe');break;}
   case 'edit-profile':showEditProfile();break;
   case 'choose-avatar':state.chosenAvatar=Math.max(1,Math.min(15,Number(id)));$$('.avatar-option').forEach(x=>{const selected=Number(x.dataset.id)===state.chosenAvatar;x.classList.toggle('selected',selected);x.setAttribute('aria-pressed',String(selected));});break;
   case 'logout':state.profile=null;save();render();toast('Tu joues maintenant en invité.');break;
   case 'preference':if(id in state.prefs){state.prefs[id]=!state.prefs[id];save();applyPreferences();if(id==='sound')Audio.sync();render();}break;
   case 'confirm-reset':openModal(modalHeader('Repartir de zéro ?')+'<p class="modal-copy">Ton pseudo, ton avatar, tes préférences et ta progression de démo seront effacés de ce navigateur. Aucun autre compte n’est concerné.</p><button class="button danger full" data-action="reset-demo">Réinitialiser la démo</button>');break;
   case 'reset-demo':resetDemo();break;
   case 'game-info':showGameInfo(id);break;
   case 'play':startGame(id);break;
   case 'close-game':closeGame();break;
   case 'restart-game':window.ArcadeGames.restart();$('#game-canvas').focus();break;
   case 'resume-game':window.ArcadeGames.resume();$('#game-canvas').focus();break;
   case 'fullscreen-game':fullScreen();break;
  }
 });
 document.addEventListener('submit',e=>{
  if(e.target.id==='auth-form'){
   e.preventDefault();const form=e.target;if(!form.reportValidity())return;
   const fields=new FormData(form);const nickname=String(fields.get('nickname')||'').trim();
   // Deliberately do not read, hash, persist or transmit the password or email.
   const display=state.authTab==='register'?nickname:(state.profile?.name||'Player One');
   if(display.length<2){$('#auth-error').textContent='Choisis un pseudo de 2 caractères minimum.';$('#auth-error').hidden=false;return;}
   state.profile={name:display.slice(0,20),avatar:state.profile?.avatar||1};save();form.reset();closeModal();if($('#app').hidden){go('arcade');if(!$('#app').hidden)updateAccount();}else render();toast('Profil de démonstration ouvert. Aucun compte en ligne n’a été créé.');
  }
  if(e.target.id==='profile-form'){e.preventDefault();if(!e.target.reportValidity())return;const name=$('#profile-name').value.trim();if(name.length<2){$('#profile-name').setCustomValidity('Choisis un pseudo de 2 caractères minimum.');$('#profile-name').reportValidity();return;}state.profile={name:name.slice(0,20),avatar:state.chosenAvatar};save();closeModal();render();toast('Ton profil a été enregistré dans ce navigateur.');}
 });
 document.addEventListener('input',e=>{if(e.target.id==='player-search'){state.search=e.target.value;$('#players-roster').innerHTML=roster();}if(e.target.id==='profile-name')e.target.setCustomValidity('');});
 document.addEventListener('change',e=>{switch(e.target.id){case 'roster-scope':state.rosterScope=e.target.value;$('#players-roster').innerHTML=roster();break;case 'roster-sort':state.sort=e.target.value;$('#players-roster').innerHTML=roster();break;case 'ranking-scope':state.scope=e.target.value;render();break;case 'ranking-world':state.world=e.target.value;render();break;}});
 $('#start-button').addEventListener('click',()=>{Audio.beep(784,.15,.03);go('arcade');});
 window.addEventListener('hashchange',()=>{const route=location.hash.slice(1);if(!route){showHome();return;}enter(route,true);});
 document.addEventListener('keydown',e=>{
  const editing=e.target.closest('input,textarea,select,[contenteditable=true]');if(editing)return;
  if(e.key==='Enter'&&!$('#splash').hidden&&!$('#modal').open&&e.target.tagName!=='BUTTON'&&e.target.tagName!=='A'){e.preventDefault();go('arcade');}
  if(e.key==='?'&&!$('#game-modal').open&&!$('#modal').open){e.preventDefault();showShortcuts();}
 });
 $('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
 $('#modal').addEventListener('close',()=>{$('#auth-form')?.reset();if(modalReturnFocus?.isConnected)modalReturnFocus.focus({preventScroll:true});});
 $('#game-modal').addEventListener('cancel',e=>{e.preventDefault();closeGame();});
 $('#game-modal').addEventListener('close',()=>{window.ArcadeGames.stop();state.activeGame=null;});
 document.addEventListener('visibilitychange',()=>{Audio.sync();if(document.hidden&&state.activeGame)window.ArcadeGames.pause();});
 window.addEventListener('blur',()=>{if(state.activeGame)window.ArcadeGames.pause();});
 window.addEventListener('pagehide',()=>{window.ArcadeGames.stop();clearInterval(Audio.timer);});
 $$('[data-pixel]').forEach(el=>el.innerHTML=D.pixelText(el.dataset.pixel));applyPreferences();
 const initial=location.hash.slice(1);if(initial)enter(initial);
 // Public, intentionally small integration surface. No auth or score write API here.
 window.WorldArcade=Object.freeze({navigate:go,launch:startGame,notify:toast,getDemoState:()=>structuredClone({profile:state.profile,completed:state.completed,prefs:state.prefs}),version:'1.0.0'});
})();
