import {chromium} from '@playwright/test';
import {readdir,readFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {openStore} from '../server/store.mjs';
import {createApp} from '../server/app.mjs';
import {previewImport,applyImport} from '../server/importer.mjs';
import {seedCatalog} from '../server/game.mjs';
import {passwordHash} from '../server/auth.mjs';
import {proposePlanChange,applyPlanChange,publishLesson,closeLesson} from '../server/domain.mjs';
import {generateLesson} from '../server/generator.mjs';
import {compileCorpus} from '../server/corpus.mjs';
const store=await openStore({path:':memory:',url:''});const actor={id:'browser-teacher',classId:'A1',role:'teacher',username:'professeur',displayName:'Professeur',passwordHash:passwordHash('browser-test-only-123')};await store.insert('teachers',actor);await seedCatalog(store);
const file=(await readdir('.')).find(n=>n.startsWith('Planification_A1_')&&n.endsWith('.xlsx'));const report=await previewImport(store,await readFile(file),actor);await applyImport(store,report.id,actor,{confirmed:true});
// Browser captures use synthetic identities even when curriculum comes from the local fixture.
for(const [i,learner] of (await store.list('learners','A1')).entries())await store.put('learners',{...learner,displayName:`Élève ${i+1}`,username:`sample-${i+1}`,email:`sample-${i+1}@example.invalid`,driveFolderId:null});
const server=createApp(store).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;
const options={headless:true};if(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE)options.executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE;
const browser=await chromium.launch(options);await mkdir('test-results',{recursive:true});const errors=[];let debugPage;
try{
 const context=await browser.newContext({viewport:{width:1440,height:1080}});const page=await context.newPage();debugPage=page;page.on('response',async r=>{if(r.status()>=400)console.log('HTTP',r.status(),r.url(),await r.text());});page.on('console',m=>{if(m.type()==='error')console.log('BROWSER',m.text());});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('#password').fill('browser-test-only-123');await page.getByRole('button',{name:'Se connecter'}).click();await page.getByRole('heading',{name:'Chaque séance fait avancer la classe.'}).waitFor();await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true});
 await page.locator('.nav [data-action=nav][data-id=lessons]').click();await page.getByRole('heading',{name:'Vos séances, prêtes à prendre vie.'}).waitFor();await page.getByText('Votre première séance commence par une intention.',{exact:true}).waitFor();assert.equal(await page.locator('#main').innerText().then(text=>text.includes('function lessonsView')),false);
 await page.locator('.nav [data-action=nav][data-id=plan]').click();await page.getByRole('heading',{name:'La planification reste vivante.'}).waitFor();await page.locator('#plan-search').fill('2026-10-08');await page.locator('[data-action=generate-entry]').first().click();await page.getByRole('heading',{name:'Confirmer le créneau'}).waitFor();await page.getByRole('button',{name:'Analyser la modification'}).click();await page.getByRole('button',{name:'Valider cette modification'}).click();await page.getByRole('heading',{name:'Avant de publier'}).waitFor({timeout:30000});await page.screenshot({path:'test-results/lesson-preview.png',fullPage:true});
 await page.getByRole('button',{name:'Retour aux séances',exact:true}).click();await page.getByRole('heading',{name:'Vos séances, prêtes à prendre vie.'}).waitFor();assert.equal(await page.locator('#main article.card').count(),1);assert.equal(await page.locator('#main').innerText().then(text=>text.includes('function lessonsView')),false);await page.getByRole('button',{name:'Ouvrir la séance',exact:true}).click();await page.getByRole('heading',{name:'Avant de publier'}).waitFor();
 await page.getByRole('button',{name:'Aperçu élève'}).click();await page.locator('#preview-body').waitFor();await page.getByRole('button',{name:'Étape suivante'}).click();assert.equal(await page.locator('#preview-body [data-component=DiagnosticIntro]').count(),1);await page.locator('[data-action=close-modal]').click();
 await page.getByRole('button',{name:'Plus pratique',exact:true}).click();await page.getByRole('heading',{name:'Relire l’adaptation'}).waitFor();await page.getByRole('button',{name:'Valider l’adaptation'}).click();await page.getByRole('heading',{name:'Avant de publier'}).waitFor();
 await page.getByRole('button',{name:'Publier cette version'}).click();await page.getByRole('button',{name:'Valider et publier'}).click();await page.getByRole('button',{name:'Clôturer la séance'}).waitFor();
 // Exercise student renderer using the published date through an intercepted today query.
 const learner=(await store.list('learners','A1'))[0];learner.passwordHash=passwordHash('student-browser-only');await store.put('learners',learner);
 const student=await browser.newContext({viewport:{width:1280,height:960}});await student.route('**/api/today',route=>route.continue({url:base+'/api/today?date=2026-10-08'}));const sp=await student.newPage();sp.on('pageerror',e=>errors.push(e.message));await sp.goto(base+'/today');await sp.getByRole('button',{name:'Élève',exact:true}).click();await sp.locator('#username').fill(learner.username);await sp.locator('#password').fill('student-browser-only');await sp.getByRole('button',{name:'Se connecter'}).click();await sp.locator('.student-stage').waitFor();await sp.screenshot({path:'test-results/student-today-desktop.png',fullPage:true});await sp.getByRole('button',{name:'Continuer',exact:true}).click();await sp.locator('[data-answer-part="baseline-valeurs"][data-part="0"]').fill('5');await sp.locator('[data-answer-part="baseline-valeurs"][data-part="1"]').fill('10');await sp.locator('[data-answer="baseline-erreur"]').fill('Le résultat attendu est 5. Je vérifierais si une valeur est du texte.');await sp.getByRole('button',{name:'Enregistrer'}).click();await sp.getByText(/Travail enregistré./).waitFor();await sp.getByRole('button',{name:'Rendre mon travail'}).click();await sp.getByRole('button',{name:'Confirmer l’envoi'}).click();await sp.locator('.lesson-receipt').filter({hasText:'Travail envoyé.'}).waitFor();await sp.screenshot({path:'test-results/student-submission.png',fullPage:true});
 const studentLesson=(await store.list('lessons','A1'))[0];const studentSpec=(await store.get('lesson_versions',studentLesson.versionId)).spec;
 if(studentSpec.codeStation){await store.insert('game_teacher_overrides',{id:'browser-world-override',classId:'A1',learnerId:learner.id,worldId:studentSpec.codeStation.worldId,enabled:true,reason:'Ouvrir la mission affectée pour ce parcours de test',authorId:actor.id});const autonomous=studentSpec.blocks.findIndex(b=>b.activityIds.includes('transfer')),game=studentSpec.blocks.findIndex(b=>b.type==='CodeStationLauncher');await sp.locator(`[data-action=student-step][data-id="${autonomous}"]:visible`).click();await sp.locator('[data-action=complete-activity][data-id=transfer]').click();await sp.getByText('Activité terminée.').waitFor();await sp.locator(`[data-action=student-step][data-id="${game}"]:visible`).click();await sp.getByRole('button',{name:'Jouer'}).click();const frame=sp.frameLocator('.game-frame');await frame.locator('#missionCode').waitFor();const original=await frame.locator('#missionCode').inputValue();await frame.locator('#missionCode').fill('while (true) {}');await frame.locator('#testScenario').click();await frame.locator('#missionResult').filter({hasText:'Temps maximal dépassé'}).waitFor();await frame.locator('#missionCode').fill(original);await frame.locator('#validateMission').click();await frame.locator('#missionResult').filter({hasText:'OK'}).waitFor();await sp.screenshot({path:'test-results/game-runtime.png',fullPage:true});await sp.locator('[data-action=close-modal]').click();console.log('Game renderer preserved; infinite loop terminated; mission event received.');}
 await page.locator('[data-action=nav][data-id=corrections]').click();await page.getByRole('button',{name:'Relire',exact:true}).click();await page.locator('input[name^="points:"]').first().waitFor();for(const input of await page.locator('input[name^="points:"]').all())await input.fill(await input.getAttribute('max'));await page.locator('input[name=reason]').fill('Validation après lecture de la production.');await page.getByRole('button',{name:'Valider cette correction'}).click();await page.getByText('Validé',{exact:true}).waitFor();
 await page.locator('[data-action=nav][data-id=dashboard]').click();await page.getByRole('heading',{name:'Chaque séance fait avancer la classe.'}).waitFor();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/dashboard-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile horizontal overflow');
 await page.setViewportSize({width:1440,height:1080});await page.locator('[data-form=intent] textarea').fill('Prépare le 2027-12-01');await page.locator('[data-form=intent] button').click();await page.getByRole('heading',{name:'Organiser les créneaux'}).waitFor();const beforeInsert=(await store.list('plan_entries','A1')).length;await page.locator('[name=objective]').fill('Atelier supplémentaire de consolidation');await page.locator('[name=skills]').fill('BC05-C1-1');await page.locator('[name=reason]').fill('Besoin pédagogique constaté');await page.getByRole('button',{name:'Analyser la proposition'}).click();await page.getByRole('heading',{name:'Relire la nouvelle planification'}).waitFor();assert.equal((await store.list('plan_entries','A1')).length,beforeInsert);await page.getByRole('button',{name:'Valider cette modification'}).click();await page.getByText('Nouvelle version de planification enregistrée.').waitFor();assert.equal((await store.list('plan_entries','A1')).length,beforeInsert+1);
 await page.locator('.nav [data-action=nav][data-id=remediation]').click();await page.getByRole('button',{name:'Observer',exact:true}).click();await page.locator('[name=criterion]').selectOption({value:'BC05-C1-1'});await page.locator('[name=level]').selectOption('EC');await page.locator('[name=note]').fill('Raisonnement correct avec un exemple guidé.');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await page.getByRole('heading',{name:'Un appui juste, au bon moment.'}).waitFor();await page.getByRole('button',{name:'Stabiliser la semaine'}).click();await page.screenshot({path:'test-results/remediation-weekly.png',fullPage:true});assert.equal((await store.list('teacher_observations','A1')).length,1);assert.equal((await store.list('remediation_snapshots','A1')).at(-1).status,'stabilized');console.log('New browser workflows passed: practice adaptation, unplanned insertion proposal and approval, observation, weekly stabilization.');
 assert.deepEqual(errors,[]);console.log('Browser flow passed: teacher login, plan approval, generation, preview, publication, student save/submit, teacher correction, mobile layout.');
}catch(e){if(debugPage){await debugPage.screenshot({path:'test-results/browser-failure.png',fullPage:true});console.log('PAGE',await debugPage.locator('body').innerText());}throw e;}finally{await browser.close();await new Promise(r=>server.close(r));await store.close();}
